/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Address type.
 */
public class Address {
    private Integer id;
    private Integer version;
    private String housePrefix;
    private String houseNo;
    private String houseSuffix;
    private String preDirectional;
    private String streetName;
    private String streetSuffix;
    private String postDirectional;
    private String addressLine2;
    private String city;
    private Integer regionId;
    private String stateCode;
    private String zip;
    private String zip4;
    private String county;
    private String country;
    private String addressType;
    private String legacyAddressId;
    private String legacyEntityId;
    private Boolean resetAddressFields;
    private String latitude;
    private String longitude;
    private AddressTypeEnum addressTypeEnum;
    private String countryWithoutDefault;
    private Boolean mNew;

    /**
     * Default constructor.
     */
    public Address() {
    }

    /**
     * Initialization constructor.
     * @param id Integer value for id.
     * @param version Integer value for version.
     * @param housePrefix String value for housePrefix.
     * @param houseNo String value for houseNo.
     * @param houseSuffix String value for houseSuffix.
     * @param preDirectional String value for preDirectional.
     * @param streetName String value for streetName.
     * @param streetSuffix String value for streetSuffix.
     * @param postDirectional String value for postDirectional.
     * @param addressLine2 String value for addressLine2.
     * @param city String value for city.
     * @param regionId Integer value for regionId.
     * @param stateCode String value for stateCode.
     * @param zip String value for zip.
     * @param zip4 String value for zip4.
     * @param county String value for county.
     * @param country String value for country.
     * @param addressType String value for addressType.
     * @param legacyAddressId String value for legacyAddressId.
     * @param legacyEntityId String value for legacyEntityId.
     * @param resetAddressFields Boolean value for resetAddressFields.
     * @param latitude String value for latitude.
     * @param longitude String value for longitude.
     * @param addressTypeEnum AddressTypeEnum value for addressTypeEnum.
     * @param countryWithoutDefault String value for countryWithoutDefault.
     * @param mNew Boolean value for mNew.
     */
    public Address(
            Integer id,
            Integer version,
            String housePrefix,
            String houseNo,
            String houseSuffix,
            String preDirectional,
            String streetName,
            String streetSuffix,
            String postDirectional,
            String addressLine2,
            String city,
            Integer regionId,
            String stateCode,
            String zip,
            String zip4,
            String county,
            String country,
            String addressType,
            String legacyAddressId,
            String legacyEntityId,
            Boolean resetAddressFields,
            String latitude,
            String longitude,
            AddressTypeEnum addressTypeEnum,
            String countryWithoutDefault,
            Boolean mNew) {
        this.id = id;
        this.version = version;
        this.housePrefix = housePrefix;
        this.houseNo = houseNo;
        this.houseSuffix = houseSuffix;
        this.preDirectional = preDirectional;
        this.streetName = streetName;
        this.streetSuffix = streetSuffix;
        this.postDirectional = postDirectional;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.regionId = regionId;
        this.stateCode = stateCode;
        this.zip = zip;
        this.zip4 = zip4;
        this.county = county;
        this.country = country;
        this.addressType = addressType;
        this.legacyAddressId = legacyAddressId;
        this.legacyEntityId = legacyEntityId;
        this.resetAddressFields = resetAddressFields;
        this.latitude = latitude;
        this.longitude = longitude;
        this.addressTypeEnum = addressTypeEnum;
        this.countryWithoutDefault = countryWithoutDefault;
        this.mNew = mNew;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @XmlElement(name = "id")
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for Version.
     * @return Returns the Integer
     */
    @JsonGetter("version")
    @XmlElement(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for Version.
     * @param version Value for Integer
     */
    @JsonSetter("version")
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * Getter for HousePrefix.
     * @return Returns the String
     */
    @JsonGetter("housePrefix")
    @XmlElement(name = "HousePrefix")
    public String getHousePrefix() {
        return this.housePrefix;
    }

    /**
     * Setter for HousePrefix.
     * @param housePrefix Value for String
     */
    @JsonSetter("housePrefix")
    public void setHousePrefix(String housePrefix) {
        this.housePrefix = housePrefix;
    }

    /**
     * Getter for HouseNo.
     * @return Returns the String
     */
    @JsonGetter("houseNo")
    @XmlElement(name = "HouseNumber")
    public String getHouseNo() {
        return this.houseNo;
    }

    /**
     * Setter for HouseNo.
     * @param houseNo Value for String
     */
    @JsonSetter("houseNo")
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }

    /**
     * Getter for HouseSuffix.
     * @return Returns the String
     */
    @JsonGetter("houseSuffix")
    @XmlElement(name = "HouseSuffix")
    public String getHouseSuffix() {
        return this.houseSuffix;
    }

    /**
     * Setter for HouseSuffix.
     * @param houseSuffix Value for String
     */
    @JsonSetter("houseSuffix")
    public void setHouseSuffix(String houseSuffix) {
        this.houseSuffix = houseSuffix;
    }

    /**
     * Getter for PreDirectional.
     * @return Returns the String
     */
    @JsonGetter("preDirectional")
    @XmlElement(name = "PreDirectional")
    public String getPreDirectional() {
        return this.preDirectional;
    }

    /**
     * Setter for PreDirectional.
     * @param preDirectional Value for String
     */
    @JsonSetter("preDirectional")
    public void setPreDirectional(String preDirectional) {
        this.preDirectional = preDirectional;
    }

    /**
     * Getter for StreetName.
     * @return Returns the String
     */
    @JsonGetter("streetName")
    @XmlElement(name = "StreetName")
    public String getStreetName() {
        return this.streetName;
    }

    /**
     * Setter for StreetName.
     * @param streetName Value for String
     */
    @JsonSetter("streetName")
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * Getter for StreetSuffix.
     * @return Returns the String
     */
    @JsonGetter("streetSuffix")
    @XmlElement(name = "StreetSuffix")
    public String getStreetSuffix() {
        return this.streetSuffix;
    }

    /**
     * Setter for StreetSuffix.
     * @param streetSuffix Value for String
     */
    @JsonSetter("streetSuffix")
    public void setStreetSuffix(String streetSuffix) {
        this.streetSuffix = streetSuffix;
    }

    /**
     * Getter for PostDirectional.
     * @return Returns the String
     */
    @JsonGetter("postDirectional")
    @XmlElement(name = "PostDirectional")
    public String getPostDirectional() {
        return this.postDirectional;
    }

    /**
     * Setter for PostDirectional.
     * @param postDirectional Value for String
     */
    @JsonSetter("postDirectional")
    public void setPostDirectional(String postDirectional) {
        this.postDirectional = postDirectional;
    }

    /**
     * Getter for AddressLine2.
     * @return Returns the String
     */
    @JsonGetter("addressLine2")
    @XmlElement(name = "AddressLine2")
    public String getAddressLine2() {
        return this.addressLine2;
    }

    /**
     * Setter for AddressLine2.
     * @param addressLine2 Value for String
     */
    @JsonSetter("addressLine2")
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * Getter for City.
     * @return Returns the String
     */
    @JsonGetter("city")
    @XmlElement(name = "City")
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for City.
     * @param city Value for String
     */
    @JsonSetter("city")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for RegionId.
     * @return Returns the Integer
     */
    @JsonGetter("regionId")
    @XmlElement(name = "regionId")
    public Integer getRegionId() {
        return this.regionId;
    }

    /**
     * Setter for RegionId.
     * @param regionId Value for Integer
     */
    @JsonSetter("regionId")
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * Getter for StateCode.
     * @return Returns the String
     */
    @JsonGetter("stateCode")
    @XmlElement(name = "StateCode")
    public String getStateCode() {
        return this.stateCode;
    }

    /**
     * Setter for StateCode.
     * @param stateCode Value for String
     */
    @JsonSetter("stateCode")
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    /**
     * Getter for Zip.
     * @return Returns the String
     */
    @JsonGetter("zip")
    @XmlElement(name = "Zip")
    public String getZip() {
        return this.zip;
    }

    /**
     * Setter for Zip.
     * @param zip Value for String
     */
    @JsonSetter("zip")
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * Getter for Zip4.
     * @return Returns the String
     */
    @JsonGetter("zip4")
    @XmlElement(name = "PlusFour")
    public String getZip4() {
        return this.zip4;
    }

    /**
     * Setter for Zip4.
     * @param zip4 Value for String
     */
    @JsonSetter("zip4")
    public void setZip4(String zip4) {
        this.zip4 = zip4;
    }

    /**
     * Getter for County.
     * @return Returns the String
     */
    @JsonGetter("county")
    @XmlElement(name = "County")
    public String getCounty() {
        return this.county;
    }

    /**
     * Setter for County.
     * @param county Value for String
     */
    @JsonSetter("county")
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * Getter for Country.
     * @return Returns the String
     */
    @JsonGetter("country")
    @XmlElement(name = "Country")
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for Country.
     * @param country Value for String
     */
    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for AddressType.
     * @return Returns the String
     */
    @JsonGetter("addressType")
    @XmlElement(name = "AddressType")
    public String getAddressType() {
        return this.addressType;
    }

    /**
     * Setter for AddressType.
     * @param addressType Value for String
     */
    @JsonSetter("addressType")
    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    /**
     * Getter for LegacyAddressId.
     * @return Returns the String
     */
    @JsonGetter("legacyAddressId")
    @XmlElement(name = "legacyAddressId")
    public String getLegacyAddressId() {
        return this.legacyAddressId;
    }

    /**
     * Setter for LegacyAddressId.
     * @param legacyAddressId Value for String
     */
    @JsonSetter("legacyAddressId")
    public void setLegacyAddressId(String legacyAddressId) {
        this.legacyAddressId = legacyAddressId;
    }

    /**
     * Getter for LegacyEntityId.
     * @return Returns the String
     */
    @JsonGetter("legacyEntityId")
    @XmlElement(name = "legacyEntityId")
    public String getLegacyEntityId() {
        return this.legacyEntityId;
    }

    /**
     * Setter for LegacyEntityId.
     * @param legacyEntityId Value for String
     */
    @JsonSetter("legacyEntityId")
    public void setLegacyEntityId(String legacyEntityId) {
        this.legacyEntityId = legacyEntityId;
    }

    /**
     * Getter for ResetAddressFields.
     * @return Returns the Boolean
     */
    @JsonGetter("resetAddressFields")
    @XmlElement(name = "ResetAddressFields")
    public Boolean getResetAddressFields() {
        return this.resetAddressFields;
    }

    /**
     * Setter for ResetAddressFields.
     * @param resetAddressFields Value for Boolean
     */
    @JsonSetter("resetAddressFields")
    public void setResetAddressFields(Boolean resetAddressFields) {
        this.resetAddressFields = resetAddressFields;
    }

    /**
     * Getter for Latitude.
     * @return Returns the String
     */
    @JsonGetter("latitude")
    @XmlElement(name = "Latitude")
    public String getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for Latitude.
     * @param latitude Value for String
     */
    @JsonSetter("latitude")
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for Longitude.
     * @return Returns the String
     */
    @JsonGetter("longitude")
    @XmlElement(name = "Longitude")
    public String getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for Longitude.
     * @param longitude Value for String
     */
    @JsonSetter("longitude")
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for AddressTypeEnum.
     * @return Returns the AddressTypeEnum
     */
    @JsonGetter("addressTypeEnum")
    @XmlElement(name = "addressTypeEnum")
    public AddressTypeEnum getAddressTypeEnum() {
        return this.addressTypeEnum;
    }

    /**
     * Setter for AddressTypeEnum.
     * @param addressTypeEnum Value for AddressTypeEnum
     */
    @JsonSetter("addressTypeEnum")
    public void setAddressTypeEnum(AddressTypeEnum addressTypeEnum) {
        this.addressTypeEnum = addressTypeEnum;
    }

    /**
     * Getter for CountryWithoutDefault.
     * @return Returns the String
     */
    @JsonGetter("countryWithoutDefault")
    @XmlElement(name = "countryWithoutDefault")
    public String getCountryWithoutDefault() {
        return this.countryWithoutDefault;
    }

    /**
     * Setter for CountryWithoutDefault.
     * @param countryWithoutDefault Value for String
     */
    @JsonSetter("countryWithoutDefault")
    public void setCountryWithoutDefault(String countryWithoutDefault) {
        this.countryWithoutDefault = countryWithoutDefault;
    }

    /**
     * Getter for New.
     * @return Returns the Boolean
     */
    @JsonGetter("new")
    @XmlElement(name = "new")
    public Boolean getNew() {
        return this.mNew;
    }

    /**
     * Setter for New.
     * @param mNew Value for Boolean
     */
    @JsonSetter("new")
    public void setNew(Boolean mNew) {
        this.mNew = mNew;
    }

    /**
     * Converts this Address into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Address [" + "id=" + id + ", version=" + version + ", housePrefix=" + housePrefix
                + ", houseNo=" + houseNo + ", houseSuffix=" + houseSuffix + ", preDirectional="
                + preDirectional + ", streetName=" + streetName + ", streetSuffix=" + streetSuffix
                + ", postDirectional=" + postDirectional + ", addressLine2=" + addressLine2
                + ", city=" + city + ", regionId=" + regionId + ", stateCode=" + stateCode
                + ", zip=" + zip + ", zip4=" + zip4 + ", county=" + county + ", country=" + country
                + ", addressType=" + addressType + ", legacyAddressId=" + legacyAddressId
                + ", legacyEntityId=" + legacyEntityId + ", resetAddressFields="
                + resetAddressFields + ", latitude=" + latitude + ", longitude=" + longitude
                + ", addressTypeEnum=" + addressTypeEnum + ", countryWithoutDefault="
                + countryWithoutDefault + ", mNew=" + mNew + "]";
    }

    /**
     * Builds a new {@link Address.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Address.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .version(getVersion())
                .housePrefix(getHousePrefix())
                .houseNo(getHouseNo())
                .houseSuffix(getHouseSuffix())
                .preDirectional(getPreDirectional())
                .streetName(getStreetName())
                .streetSuffix(getStreetSuffix())
                .postDirectional(getPostDirectional())
                .addressLine2(getAddressLine2())
                .city(getCity())
                .regionId(getRegionId())
                .stateCode(getStateCode())
                .zip(getZip())
                .zip4(getZip4())
                .county(getCounty())
                .country(getCountry())
                .addressType(getAddressType())
                .legacyAddressId(getLegacyAddressId())
                .legacyEntityId(getLegacyEntityId())
                .resetAddressFields(getResetAddressFields())
                .latitude(getLatitude())
                .longitude(getLongitude())
                .addressTypeEnum(getAddressTypeEnum())
                .countryWithoutDefault(getCountryWithoutDefault())
                .mNew(getNew());
        return builder;
    }

    /**
     * Class to build instances of {@link Address}.
     */
    public static class Builder {
        private Integer id;
        private Integer version;
        private String housePrefix;
        private String houseNo;
        private String houseSuffix;
        private String preDirectional;
        private String streetName;
        private String streetSuffix;
        private String postDirectional;
        private String addressLine2;
        private String city;
        private Integer regionId;
        private String stateCode;
        private String zip;
        private String zip4;
        private String county;
        private String country;
        private String addressType;
        private String legacyAddressId;
        private String legacyEntityId;
        private Boolean resetAddressFields;
        private String latitude;
        private String longitude;
        private AddressTypeEnum addressTypeEnum;
        private String countryWithoutDefault;
        private Boolean mNew;



        /**
         * Setter for id.
         * @param id Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for version.
         * @param version Integer value for version.
         * @return Builder
         */
        public Builder version(Integer version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for housePrefix.
         * @param housePrefix String value for housePrefix.
         * @return Builder
         */
        public Builder housePrefix(String housePrefix) {
            this.housePrefix = housePrefix;
            return this;
        }

        /**
         * Setter for houseNo.
         * @param houseNo String value for houseNo.
         * @return Builder
         */
        public Builder houseNo(String houseNo) {
            this.houseNo = houseNo;
            return this;
        }

        /**
         * Setter for houseSuffix.
         * @param houseSuffix String value for houseSuffix.
         * @return Builder
         */
        public Builder houseSuffix(String houseSuffix) {
            this.houseSuffix = houseSuffix;
            return this;
        }

        /**
         * Setter for preDirectional.
         * @param preDirectional String value for preDirectional.
         * @return Builder
         */
        public Builder preDirectional(String preDirectional) {
            this.preDirectional = preDirectional;
            return this;
        }

        /**
         * Setter for streetName.
         * @param streetName String value for streetName.
         * @return Builder
         */
        public Builder streetName(String streetName) {
            this.streetName = streetName;
            return this;
        }

        /**
         * Setter for streetSuffix.
         * @param streetSuffix String value for streetSuffix.
         * @return Builder
         */
        public Builder streetSuffix(String streetSuffix) {
            this.streetSuffix = streetSuffix;
            return this;
        }

        /**
         * Setter for postDirectional.
         * @param postDirectional String value for postDirectional.
         * @return Builder
         */
        public Builder postDirectional(String postDirectional) {
            this.postDirectional = postDirectional;
            return this;
        }

        /**
         * Setter for addressLine2.
         * @param addressLine2 String value for addressLine2.
         * @return Builder
         */
        public Builder addressLine2(String addressLine2) {
            this.addressLine2 = addressLine2;
            return this;
        }

        /**
         * Setter for city.
         * @param city String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for regionId.
         * @param regionId Integer value for regionId.
         * @return Builder
         */
        public Builder regionId(Integer regionId) {
            this.regionId = regionId;
            return this;
        }

        /**
         * Setter for stateCode.
         * @param stateCode String value for stateCode.
         * @return Builder
         */
        public Builder stateCode(String stateCode) {
            this.stateCode = stateCode;
            return this;
        }

        /**
         * Setter for zip.
         * @param zip String value for zip.
         * @return Builder
         */
        public Builder zip(String zip) {
            this.zip = zip;
            return this;
        }

        /**
         * Setter for zip4.
         * @param zip4 String value for zip4.
         * @return Builder
         */
        public Builder zip4(String zip4) {
            this.zip4 = zip4;
            return this;
        }

        /**
         * Setter for county.
         * @param county String value for county.
         * @return Builder
         */
        public Builder county(String county) {
            this.county = county;
            return this;
        }

        /**
         * Setter for country.
         * @param country String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for addressType.
         * @param addressType String value for addressType.
         * @return Builder
         */
        public Builder addressType(String addressType) {
            this.addressType = addressType;
            return this;
        }

        /**
         * Setter for legacyAddressId.
         * @param legacyAddressId String value for legacyAddressId.
         * @return Builder
         */
        public Builder legacyAddressId(String legacyAddressId) {
            this.legacyAddressId = legacyAddressId;
            return this;
        }

        /**
         * Setter for legacyEntityId.
         * @param legacyEntityId String value for legacyEntityId.
         * @return Builder
         */
        public Builder legacyEntityId(String legacyEntityId) {
            this.legacyEntityId = legacyEntityId;
            return this;
        }

        /**
         * Setter for resetAddressFields.
         * @param resetAddressFields Boolean value for resetAddressFields.
         * @return Builder
         */
        public Builder resetAddressFields(Boolean resetAddressFields) {
            this.resetAddressFields = resetAddressFields;
            return this;
        }

        /**
         * Setter for latitude.
         * @param latitude String value for latitude.
         * @return Builder
         */
        public Builder latitude(String latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Setter for longitude.
         * @param longitude String value for longitude.
         * @return Builder
         */
        public Builder longitude(String longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * Setter for addressTypeEnum.
         * @param addressTypeEnum AddressTypeEnum value for addressTypeEnum.
         * @return Builder
         */
        public Builder addressTypeEnum(AddressTypeEnum addressTypeEnum) {
            this.addressTypeEnum = addressTypeEnum;
            return this;
        }

        /**
         * Setter for countryWithoutDefault.
         * @param countryWithoutDefault String value for countryWithoutDefault.
         * @return Builder
         */
        public Builder countryWithoutDefault(String countryWithoutDefault) {
            this.countryWithoutDefault = countryWithoutDefault;
            return this;
        }

        /**
         * Setter for mNew.
         * @param mNew Boolean value for mNew.
         * @return Builder
         */
        public Builder mNew(Boolean mNew) {
            this.mNew = mNew;
            return this;
        }

        /**
         * Builds a new {@link Address} object using the set fields.
         * @return {@link Address}
         */
        public Address build() {
            return new Address(id, version, housePrefix, houseNo, houseSuffix, preDirectional,
                    streetName, streetSuffix, postDirectional, addressLine2, city, regionId,
                    stateCode, zip, zip4, county, country, addressType, legacyAddressId,
                    legacyEntityId, resetAddressFields, latitude, longitude, addressTypeEnum,
                    countryWithoutDefault, mNew);
        }
    }
}
