/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for ApplicationResponse type.
 */
public class ApplicationResponse {
    private ApplicationPayload payload;

    /**
     * Default constructor.
     */
    public ApplicationResponse() {
    }

    /**
     * Initialization constructor.
     * @param payload ApplicationPayload value for payload.
     */
    public ApplicationResponse(
            ApplicationPayload payload) {
        this.payload = payload;
    }

    /**
     * Getter for Payload.
     * @return Returns the ApplicationPayload
     */
    @JsonGetter("payload")
    @XmlElement(name = "Application")
    public ApplicationPayload getPayload() {
        return this.payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for ApplicationPayload
     */
    @JsonSetter("payload")
    public void setPayload(ApplicationPayload payload) {
        this.payload = payload;
    }

    /**
     * Converts this ApplicationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ApplicationResponse [" + "payload=" + payload + "]";
    }

    /**
     * Builds a new {@link ApplicationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ApplicationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload());
        return builder;
    }

    /**
     * Class to build instances of {@link ApplicationResponse}.
     */
    public static class Builder {
        private ApplicationPayload payload;



        /**
         * Setter for payload.
         * @param payload ApplicationPayload value for payload.
         * @return Builder
         */
        public Builder payload(ApplicationPayload payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Builds a new {@link ApplicationResponse} object using the set fields.
         * @return {@link ApplicationResponse}
         */
        public ApplicationResponse build() {
            return new ApplicationResponse(payload);
        }
    }
}
