/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for BillingReportArchiveRetrievalResponse type.
 */
public class BillingReportArchiveRetrievalResponse {
    private String reportStatus;
    private String description;

    /**
     * Default constructor.
     */
    public BillingReportArchiveRetrievalResponse() {
    }

    /**
     * Initialization constructor.
     * @param reportStatus String value for reportStatus.
     * @param description String value for description.
     */
    public BillingReportArchiveRetrievalResponse(
            String reportStatus,
            String description) {
        this.reportStatus = reportStatus;
        this.description = description;
    }

    /**
     * Getter for ReportStatus.
     * @return Returns the String
     */
    @JsonGetter("reportStatus")
    @XmlElement(name = "ReportStatus")
    public String getReportStatus() {
        return this.reportStatus;
    }

    /**
     * Setter for ReportStatus.
     * @param reportStatus Value for String
     */
    @JsonSetter("reportStatus")
    public void setReportStatus(String reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @XmlElement(name = "Description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this BillingReportArchiveRetrievalResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BillingReportArchiveRetrievalResponse [" + "reportStatus=" + reportStatus
                + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link BillingReportArchiveRetrievalResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BillingReportArchiveRetrievalResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .reportStatus(getReportStatus())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link BillingReportArchiveRetrievalResponse}.
     */
    public static class Builder {
        private String reportStatus;
        private String description;



        /**
         * Setter for reportStatus.
         * @param reportStatus String value for reportStatus.
         * @return Builder
         */
        public Builder reportStatus(String reportStatus) {
            this.reportStatus = reportStatus;
            return this;
        }

        /**
         * Setter for description.
         * @param description String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link BillingReportArchiveRetrievalResponse} object using the set fields.
         * @return {@link BillingReportArchiveRetrievalResponse}
         */
        public BillingReportArchiveRetrievalResponse build() {
            return new BillingReportArchiveRetrievalResponse(reportStatus, description);
        }
    }
}
