/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for LdapPermission type.
 */
public class LdapPermission {
    private String permissionId;
    private String description;
    private Boolean internal;

    /**
     * Default constructor.
     */
    public LdapPermission() {
    }

    /**
     * Initialization constructor.
     * @param permissionId String value for permissionId.
     * @param description String value for description.
     * @param internal Boolean value for internal.
     */
    public LdapPermission(
            String permissionId,
            String description,
            Boolean internal) {
        this.permissionId = permissionId;
        this.description = description;
        this.internal = internal;
    }

    /**
     * Getter for PermissionId.
     * @return Returns the String
     */
    @JsonGetter("permissionId")
    @XmlElement(name = "PermissionId")
    public String getPermissionId() {
        return this.permissionId;
    }

    /**
     * Setter for PermissionId.
     * @param permissionId Value for String
     */
    @JsonSetter("permissionId")
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @XmlElement(name = "PermissionDescription")
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Internal.
     * @return Returns the Boolean
     */
    @JsonGetter("internal")
    @XmlElement(name = "Internal")
    public Boolean getInternal() {
        return this.internal;
    }

    /**
     * Setter for Internal.
     * @param internal Value for Boolean
     */
    @JsonSetter("internal")
    public void setInternal(Boolean internal) {
        this.internal = internal;
    }

    /**
     * Converts this LdapPermission into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LdapPermission [" + "permissionId=" + permissionId + ", description=" + description
                + ", internal=" + internal + "]";
    }

    /**
     * Builds a new {@link LdapPermission.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LdapPermission.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .permissionId(getPermissionId())
                .description(getDescription())
                .internal(getInternal());
        return builder;
    }

    /**
     * Class to build instances of {@link LdapPermission}.
     */
    public static class Builder {
        private String permissionId;
        private String description;
        private Boolean internal;



        /**
         * Setter for permissionId.
         * @param permissionId String value for permissionId.
         * @return Builder
         */
        public Builder permissionId(String permissionId) {
            this.permissionId = permissionId;
            return this;
        }

        /**
         * Setter for description.
         * @param description String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for internal.
         * @param internal Boolean value for internal.
         * @return Builder
         */
        public Builder internal(Boolean internal) {
            this.internal = internal;
            return this;
        }

        /**
         * Builds a new {@link LdapPermission} object using the set fields.
         * @return {@link LdapPermission}
         */
        public LdapPermission build() {
            return new LdapPermission(permissionId, description, internal);
        }
    }
}
