/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for MmsProtocols type.
 */
public class MmsProtocols {
    private MmsMM4Protocol mm4Protocol;
    private MmsHttpProtocol httpProtocol;

    /**
     * Default constructor.
     */
    public MmsProtocols() {
    }

    /**
     * Initialization constructor.
     * @param mm4Protocol MmsMM4Protocol value for mm4Protocol.
     * @param httpProtocol MmsHttpProtocol value for httpProtocol.
     */
    public MmsProtocols(
            MmsMM4Protocol mm4Protocol,
            MmsHttpProtocol httpProtocol) {
        this.mm4Protocol = mm4Protocol;
        this.httpProtocol = httpProtocol;
    }

    /**
     * Getter for Mm4Protocol.
     * @return Returns the MmsMM4Protocol
     */
    @JsonGetter("mm4Protocol")
    @XmlElement(name = "MM4")
    public MmsMM4Protocol getMm4Protocol() {
        return this.mm4Protocol;
    }

    /**
     * Setter for Mm4Protocol.
     * @param mm4Protocol Value for MmsMM4Protocol
     */
    @JsonSetter("mm4Protocol")
    public void setMm4Protocol(MmsMM4Protocol mm4Protocol) {
        this.mm4Protocol = mm4Protocol;
    }

    /**
     * Getter for HttpProtocol.
     * @return Returns the MmsHttpProtocol
     */
    @JsonGetter("httpProtocol")
    @XmlElement(name = "HTTP")
    public MmsHttpProtocol getHttpProtocol() {
        return this.httpProtocol;
    }

    /**
     * Setter for HttpProtocol.
     * @param httpProtocol Value for MmsHttpProtocol
     */
    @JsonSetter("httpProtocol")
    public void setHttpProtocol(MmsHttpProtocol httpProtocol) {
        this.httpProtocol = httpProtocol;
    }

    /**
     * Converts this MmsProtocols into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MmsProtocols [" + "mm4Protocol=" + mm4Protocol + ", httpProtocol=" + httpProtocol
                + "]";
    }

    /**
     * Builds a new {@link MmsProtocols.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MmsProtocols.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .mm4Protocol(getMm4Protocol())
                .httpProtocol(getHttpProtocol());
        return builder;
    }

    /**
     * Class to build instances of {@link MmsProtocols}.
     */
    public static class Builder {
        private MmsMM4Protocol mm4Protocol;
        private MmsHttpProtocol httpProtocol;



        /**
         * Setter for mm4Protocol.
         * @param mm4Protocol MmsMM4Protocol value for mm4Protocol.
         * @return Builder
         */
        public Builder mm4Protocol(MmsMM4Protocol mm4Protocol) {
            this.mm4Protocol = mm4Protocol;
            return this;
        }

        /**
         * Setter for httpProtocol.
         * @param httpProtocol MmsHttpProtocol value for httpProtocol.
         * @return Builder
         */
        public Builder httpProtocol(MmsHttpProtocol httpProtocol) {
            this.httpProtocol = httpProtocol;
            return this;
        }

        /**
         * Builds a new {@link MmsProtocols} object using the set fields.
         * @return {@link MmsProtocols}
         */
        public MmsProtocols build() {
            return new MmsProtocols(mm4Protocol, httpProtocol);
        }
    }
}
