/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PaginationLinks type.
 */
public class PaginationLinks {
    private String first;
    private String next;
    private String previous;
    private String last;

    /**
     * Default constructor.
     */
    public PaginationLinks() {
    }

    /**
     * Initialization constructor.
     * @param first String value for first.
     * @param next String value for next.
     * @param previous String value for previous.
     * @param last String value for last.
     */
    public PaginationLinks(
            String first,
            String next,
            String previous,
            String last) {
        this.first = first;
        this.next = next;
        this.previous = previous;
        this.last = last;
    }

    /**
     * Getter for First.
     * @return Returns the String
     */
    @JsonGetter("first")
    @XmlElement(name = "first")
    public String getFirst() {
        return this.first;
    }

    /**
     * Setter for First.
     * @param first Value for String
     */
    @JsonSetter("first")
    public void setFirst(String first) {
        this.first = first;
    }

    /**
     * Getter for Next.
     * @return Returns the String
     */
    @JsonGetter("next")
    @XmlElement(name = "next")
    public String getNext() {
        return this.next;
    }

    /**
     * Setter for Next.
     * @param next Value for String
     */
    @JsonSetter("next")
    public void setNext(String next) {
        this.next = next;
    }

    /**
     * Getter for Previous.
     * @return Returns the String
     */
    @JsonGetter("previous")
    @XmlElement(name = "previous")
    public String getPrevious() {
        return this.previous;
    }

    /**
     * Setter for Previous.
     * @param previous Value for String
     */
    @JsonSetter("previous")
    public void setPrevious(String previous) {
        this.previous = previous;
    }

    /**
     * Getter for Last.
     * @return Returns the String
     */
    @JsonGetter("last")
    @XmlElement(name = "last")
    public String getLast() {
        return this.last;
    }

    /**
     * Setter for Last.
     * @param last Value for String
     */
    @JsonSetter("last")
    public void setLast(String last) {
        this.last = last;
    }

    /**
     * Converts this PaginationLinks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaginationLinks [" + "first=" + first + ", next=" + next + ", previous=" + previous
                + ", last=" + last + "]";
    }

    /**
     * Builds a new {@link PaginationLinks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaginationLinks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .first(getFirst())
                .next(getNext())
                .previous(getPrevious())
                .last(getLast());
        return builder;
    }

    /**
     * Class to build instances of {@link PaginationLinks}.
     */
    public static class Builder {
        private String first;
        private String next;
        private String previous;
        private String last;



        /**
         * Setter for first.
         * @param first String value for first.
         * @return Builder
         */
        public Builder first(String first) {
            this.first = first;
            return this;
        }

        /**
         * Setter for next.
         * @param next String value for next.
         * @return Builder
         */
        public Builder next(String next) {
            this.next = next;
            return this;
        }

        /**
         * Setter for previous.
         * @param previous String value for previous.
         * @return Builder
         */
        public Builder previous(String previous) {
            this.previous = previous;
            return this;
        }

        /**
         * Setter for last.
         * @param last String value for last.
         * @return Builder
         */
        public Builder last(String last) {
            this.last = last;
            return this;
        }

        /**
         * Builds a new {@link PaginationLinks} object using the set fields.
         * @return {@link PaginationLinks}
         */
        public PaginationLinks build() {
            return new PaginationLinks(first, next, previous, last);
        }
    }
}
