/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for PhoneNumberList type.
 */
public class PhoneNumberList {
    private List<PhoneNumber> phoneNumbers;
    private List<String> numbersAsStrings;

    /**
     * Default constructor.
     */
    public PhoneNumberList() {
    }

    /**
     * Initialization constructor.
     * @param phoneNumbers List of PhoneNumber value for phoneNumbers.
     * @param numbersAsStrings List of String value for numbersAsStrings.
     */
    public PhoneNumberList(
            List<PhoneNumber> phoneNumbers,
            List<String> numbersAsStrings) {
        this.phoneNumbers = phoneNumbers;
        this.numbersAsStrings = numbersAsStrings;
    }

    /**
     * Getter for PhoneNumbers.
     * @return Returns the List of PhoneNumber
     */
    @JsonGetter("phoneNumbers")
    @XmlElement(name = "PhoneNumber")
    public List<PhoneNumber> getPhoneNumbers() {
        return this.phoneNumbers;
    }

    /**
     * Setter for PhoneNumbers.
     * @param phoneNumbers Value for List of PhoneNumber
     */
    @JsonSetter("phoneNumbers")
    public void setPhoneNumbers(List<PhoneNumber> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    /**
     * Getter for NumbersAsStrings.
     * @return Returns the List of String
     */
    @JsonGetter("numbersAsStrings")
    @XmlElement(name = "TnAttribute")
    public List<String> getNumbersAsStrings() {
        return this.numbersAsStrings;
    }

    /**
     * Setter for NumbersAsStrings.
     * @param numbersAsStrings Value for List of String
     */
    @JsonSetter("numbersAsStrings")
    public void setNumbersAsStrings(List<String> numbersAsStrings) {
        this.numbersAsStrings = numbersAsStrings;
    }

    /**
     * Converts this PhoneNumberList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PhoneNumberList [" + "phoneNumbers=" + phoneNumbers + ", numbersAsStrings="
                + numbersAsStrings + "]";
    }

    /**
     * Builds a new {@link PhoneNumberList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PhoneNumberList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .phoneNumbers(getPhoneNumbers())
                .numbersAsStrings(getNumbersAsStrings());
        return builder;
    }

    /**
     * Class to build instances of {@link PhoneNumberList}.
     */
    public static class Builder {
        private List<PhoneNumber> phoneNumbers;
        private List<String> numbersAsStrings;



        /**
         * Setter for phoneNumbers.
         * @param phoneNumbers List of PhoneNumber value for phoneNumbers.
         * @return Builder
         */
        public Builder phoneNumbers(List<PhoneNumber> phoneNumbers) {
            this.phoneNumbers = phoneNumbers;
            return this;
        }

        /**
         * Setter for numbersAsStrings.
         * @param numbersAsStrings List of String value for numbersAsStrings.
         * @return Builder
         */
        public Builder numbersAsStrings(List<String> numbersAsStrings) {
            this.numbersAsStrings = numbersAsStrings;
            return this;
        }

        /**
         * Builds a new {@link PhoneNumberList} object using the set fields.
         * @return {@link PhoneNumberList}
         */
        public PhoneNumberList build() {
            return new PhoneNumberList(phoneNumbers, numbersAsStrings);
        }
    }
}
