/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Region type.
 */
public class Region {
    private String abbreviation;
    private String name;

    /**
     * Default constructor.
     */
    public Region() {
    }

    /**
     * Initialization constructor.
     * @param abbreviation String value for abbreviation.
     * @param name String value for name.
     */
    public Region(
            String abbreviation,
            String name) {
        this.abbreviation = abbreviation;
        this.name = name;
    }

    /**
     * Getter for Abbreviation.
     * @return Returns the String
     */
    @JsonGetter("abbreviation")
    @XmlElement(name = "Abbreviation")
    public String getAbbreviation() {
        return this.abbreviation;
    }

    /**
     * Setter for Abbreviation.
     * @param abbreviation Value for String
     */
    @JsonSetter("abbreviation")
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @XmlElement(name = "name")
    public String getName() {
        return this.name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Converts this Region into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Region [" + "abbreviation=" + abbreviation + ", name=" + name + "]";
    }

    /**
     * Builds a new {@link Region.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Region.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(abbreviation)
                .name(getName());
        return builder;
    }

    /**
     * Class to build instances of {@link Region}.
     */
    public static class Builder {
        private String abbreviation;
        private String name;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param abbreviation String value for abbreviation.
         */
        public Builder(String abbreviation) {
            this.abbreviation = abbreviation;
        }

        /**
         * Setter for abbreviation.
         * @param abbreviation String value for abbreviation.
         * @return Builder
         */
        public Builder abbreviation(String abbreviation) {
            this.abbreviation = abbreviation;
            return this;
        }

        /**
         * Setter for name.
         * @param name String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Builds a new {@link Region} object using the set fields.
         * @return {@link Region}
         */
        public Region build() {
            return new Region(abbreviation, name);
        }
    }
}
