/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for SipPeerGatewayIpsResponse type.
 */
public class SipPeerGatewayIpsResponse {
    private Payload4 payload;

    /**
     * Default constructor.
     */
    public SipPeerGatewayIpsResponse() {
    }

    /**
     * Initialization constructor.
     * @param payload Payload4 value for payload.
     */
    public SipPeerGatewayIpsResponse(
            Payload4 payload) {
        this.payload = payload;
    }

    /**
     * Getter for Payload.
     * @return Returns the Payload4
     */
    @JsonGetter("payload")
    @XmlElement(name = "TerminationHost")
    public Payload4 getPayload() {
        return this.payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for Payload4
     */
    @JsonSetter("payload")
    public void setPayload(Payload4 payload) {
        this.payload = payload;
    }

    /**
     * Converts this SipPeerGatewayIpsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SipPeerGatewayIpsResponse [" + "payload=" + payload + "]";
    }

    /**
     * Builds a new {@link SipPeerGatewayIpsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SipPeerGatewayIpsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload());
        return builder;
    }

    /**
     * Class to build instances of {@link SipPeerGatewayIpsResponse}.
     */
    public static class Builder {
        private Payload4 payload;



        /**
         * Setter for payload.
         * @param payload Payload4 value for payload.
         * @return Builder
         */
        public Builder payload(Payload4 payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Builds a new {@link SipPeerGatewayIpsResponse} object using the set fields.
         * @return {@link SipPeerGatewayIpsResponse}
         */
        public SipPeerGatewayIpsResponse build() {
            return new SipPeerGatewayIpsResponse(payload);
        }
    }
}
