/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for SiteContract type.
 */
public class SiteContract {
    private SiteSalesRepresentative salesRepresentative;
    private SiteContactPerson contactPerson;

    /**
     * Default constructor.
     */
    public SiteContract() {
    }

    /**
     * Initialization constructor.
     * @param salesRepresentative SiteSalesRepresentative value for salesRepresentative.
     * @param contactPerson SiteContactPerson value for contactPerson.
     */
    public SiteContract(
            SiteSalesRepresentative salesRepresentative,
            SiteContactPerson contactPerson) {
        this.salesRepresentative = salesRepresentative;
        this.contactPerson = contactPerson;
    }

    /**
     * Getter for SalesRepresentative.
     * @return Returns the SiteSalesRepresentative
     */
    @JsonGetter("salesRepresentative")
    @XmlElement(name = "SalesRepresentative")
    public SiteSalesRepresentative getSalesRepresentative() {
        return this.salesRepresentative;
    }

    /**
     * Setter for SalesRepresentative.
     * @param salesRepresentative Value for SiteSalesRepresentative
     */
    @JsonSetter("salesRepresentative")
    public void setSalesRepresentative(SiteSalesRepresentative salesRepresentative) {
        this.salesRepresentative = salesRepresentative;
    }

    /**
     * Getter for ContactPerson.
     * @return Returns the SiteContactPerson
     */
    @JsonGetter("contactPerson")
    @XmlElement(name = "ContactPerson")
    public SiteContactPerson getContactPerson() {
        return this.contactPerson;
    }

    /**
     * Setter for ContactPerson.
     * @param contactPerson Value for SiteContactPerson
     */
    @JsonSetter("contactPerson")
    public void setContactPerson(SiteContactPerson contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * Converts this SiteContract into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SiteContract [" + "salesRepresentative=" + salesRepresentative + ", contactPerson="
                + contactPerson + "]";
    }

    /**
     * Builds a new {@link SiteContract.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SiteContract.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .salesRepresentative(getSalesRepresentative())
                .contactPerson(getContactPerson());
        return builder;
    }

    /**
     * Class to build instances of {@link SiteContract}.
     */
    public static class Builder {
        private SiteSalesRepresentative salesRepresentative;
        private SiteContactPerson contactPerson;



        /**
         * Setter for salesRepresentative.
         * @param salesRepresentative SiteSalesRepresentative value for salesRepresentative.
         * @return Builder
         */
        public Builder salesRepresentative(SiteSalesRepresentative salesRepresentative) {
            this.salesRepresentative = salesRepresentative;
            return this;
        }

        /**
         * Setter for contactPerson.
         * @param contactPerson SiteContactPerson value for contactPerson.
         * @return Builder
         */
        public Builder contactPerson(SiteContactPerson contactPerson) {
            this.contactPerson = contactPerson;
            return this;
        }

        /**
         * Builds a new {@link SiteContract} object using the set fields.
         * @return {@link SiteContract}
         */
        public SiteContract build() {
            return new SiteContract(salesRepresentative, contactPerson);
        }
    }
}
