/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for SiteLockResponse type.
 */
public class SiteLockResponse {
    private SiteLock payload;

    /**
     * Default constructor.
     */
    public SiteLockResponse() {
    }

    /**
     * Initialization constructor.
     * @param payload SiteLock value for payload.
     */
    public SiteLockResponse(
            SiteLock payload) {
        this.payload = payload;
    }

    /**
     * Getter for Payload.
     * @return Returns the SiteLock
     */
    @JsonGetter("payload")
    @XmlElement(name = "Lock")
    public SiteLock getPayload() {
        return this.payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for SiteLock
     */
    @JsonSetter("payload")
    public void setPayload(SiteLock payload) {
        this.payload = payload;
    }

    /**
     * Converts this SiteLockResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SiteLockResponse [" + "payload=" + payload + "]";
    }

    /**
     * Builds a new {@link SiteLockResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SiteLockResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload());
        return builder;
    }

    /**
     * Class to build instances of {@link SiteLockResponse}.
     */
    public static class Builder {
        private SiteLock payload;



        /**
         * Setter for payload.
         * @param payload SiteLock value for payload.
         * @return Builder
         */
        public Builder payload(SiteLock payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Builds a new {@link SiteLockResponse} object using the set fields.
         * @return {@link SiteLockResponse}
         */
        public SiteLockResponse build() {
            return new SiteLockResponse(payload);
        }
    }
}
