/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for TerminationRoutingExceptionResponse type.
 */
public class TerminationRoutingExceptionResponse {
    private TerminationRoutingException payload;

    /**
     * Default constructor.
     */
    public TerminationRoutingExceptionResponse() {
    }

    /**
     * Initialization constructor.
     * @param payload TerminationRoutingException value for payload.
     */
    public TerminationRoutingExceptionResponse(
            TerminationRoutingException payload) {
        this.payload = payload;
    }

    /**
     * Getter for Payload.
     * @return Returns the TerminationRoutingException
     */
    @JsonGetter("payload")
    @XmlElement(name = "TerminationRoutingException")
    public TerminationRoutingException getPayload() {
        return this.payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for TerminationRoutingException
     */
    @JsonSetter("payload")
    public void setPayload(TerminationRoutingException payload) {
        this.payload = payload;
    }

    /**
     * Converts this TerminationRoutingExceptionResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TerminationRoutingExceptionResponse [" + "payload=" + payload + "]";
    }

    /**
     * Builds a new {@link TerminationRoutingExceptionResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TerminationRoutingExceptionResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload());
        return builder;
    }

    /**
     * Class to build instances of {@link TerminationRoutingExceptionResponse}.
     */
    public static class Builder {
        private TerminationRoutingException payload;



        /**
         * Setter for payload.
         * @param payload TerminationRoutingException value for payload.
         * @return Builder
         */
        public Builder payload(TerminationRoutingException payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Builds a new {@link TerminationRoutingExceptionResponse} object using the set fields.
         * @return {@link TerminationRoutingExceptionResponse}
         */
        public TerminationRoutingExceptionResponse build() {
            return new TerminationRoutingExceptionResponse(payload);
        }
    }
}
