/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.iris.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for TnPortOutPasscodesResponse type.
 */
public class TnPortOutPasscodesResponse {
    private TnPortOutPasscodesPayload payload;
    private PaginationLinks paginationLinks;
    private List<TelephoneNumberGroupError> errorList;

    /**
     * Default constructor.
     */
    public TnPortOutPasscodesResponse() {
    }

    /**
     * Initialization constructor.
     * @param payload TnPortOutPasscodesPayload value for payload.
     * @param paginationLinks PaginationLinks value for paginationLinks.
     * @param errorList List of TelephoneNumberGroupError value for errorList.
     */
    public TnPortOutPasscodesResponse(
            TnPortOutPasscodesPayload payload,
            PaginationLinks paginationLinks,
            List<TelephoneNumberGroupError> errorList) {
        this.payload = payload;
        this.paginationLinks = paginationLinks;
        this.errorList = errorList;
    }

    /**
     * Getter for Payload.
     * @return Returns the TnPortOutPasscodesPayload
     */
    @JsonGetter("payload")
    @XmlElement(name = "TelephoneNumbers")
    public TnPortOutPasscodesPayload getPayload() {
        return this.payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for TnPortOutPasscodesPayload
     */
    @JsonSetter("payload")
    public void setPayload(TnPortOutPasscodesPayload payload) {
        this.payload = payload;
    }

    /**
     * Getter for PaginationLinks.
     * @return Returns the PaginationLinks
     */
    @JsonGetter("paginationLinks")
    @XmlElement(name = "Links")
    public PaginationLinks getPaginationLinks() {
        return this.paginationLinks;
    }

    /**
     * Setter for PaginationLinks.
     * @param paginationLinks Value for PaginationLinks
     */
    @JsonSetter("paginationLinks")
    public void setPaginationLinks(PaginationLinks paginationLinks) {
        this.paginationLinks = paginationLinks;
    }

    /**
     * Getter for ErrorList.
     * @return Returns the List of TelephoneNumberGroupError
     */
    @JsonGetter("errorList")
    @XmlElementWrapper(name = "ErrorList")
    @XmlElement(name = "Error")
    public List<TelephoneNumberGroupError> getErrorList() {
        return this.errorList;
    }

    /**
     * Setter for ErrorList.
     * @param errorList Value for List of TelephoneNumberGroupError
     */
    @JsonSetter("errorList")
    public void setErrorList(List<TelephoneNumberGroupError> errorList) {
        this.errorList = errorList;
    }

    /**
     * Converts this TnPortOutPasscodesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TnPortOutPasscodesResponse [" + "payload=" + payload + ", paginationLinks="
                + paginationLinks + ", errorList=" + errorList + "]";
    }

    /**
     * Builds a new {@link TnPortOutPasscodesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TnPortOutPasscodesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload())
                .paginationLinks(getPaginationLinks())
                .errorList(getErrorList());
        return builder;
    }

    /**
     * Class to build instances of {@link TnPortOutPasscodesResponse}.
     */
    public static class Builder {
        private TnPortOutPasscodesPayload payload;
        private PaginationLinks paginationLinks;
        private List<TelephoneNumberGroupError> errorList;



        /**
         * Setter for payload.
         * @param payload TnPortOutPasscodesPayload value for payload.
         * @return Builder
         */
        public Builder payload(TnPortOutPasscodesPayload payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Setter for paginationLinks.
         * @param paginationLinks PaginationLinks value for paginationLinks.
         * @return Builder
         */
        public Builder paginationLinks(PaginationLinks paginationLinks) {
            this.paginationLinks = paginationLinks;
            return this;
        }

        /**
         * Setter for errorList.
         * @param errorList List of TelephoneNumberGroupError value for errorList.
         * @return Builder
         */
        public Builder errorList(List<TelephoneNumberGroupError> errorList) {
            this.errorList = errorList;
            return this;
        }

        /**
         * Builds a new {@link TnPortOutPasscodesResponse} object using the set fields.
         * @return {@link TnPortOutPasscodesResponse}
         */
        public TnPortOutPasscodesResponse build() {
            return new TnPortOutPasscodesResponse(payload, paginationLinks, errorList);
        }
    }
}
