artifactId: bandwidth-sdk
artifactDescription: The official client SDK for Bandwidth's Voice, Messaging, MFA, and WebRTC APIs
artifactUrl: https://github.com/Bandwidth/java-sdk
developerName: Bandwidth Support
developerEmail: info@bandwidth.com
developerOrganization: Bandwidth Inc
developerOrganizationUrl: http://bandwidth.com
disallowAdditionalPropertiesIfNotPresent: false
hideGenerationTimestamp: true
groupId: com.bandwidth.sdk
invokerPackage: com.bandwidth.sdk
apiPackage: com.bandwidth.sdk.api
modelPackage: com.bandwidth.sdk.model
library: okhttp-gson
licenseName: MIT
useEnumCaseInsensitive: true
useOneOfDiscriminatorLookup: true
templateDir: custom_templates
