/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.phonenumberlookup.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OrderResponse type.
 */
public class OrderResponse {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String requestId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;

    /**
     * Default constructor.
     */
    public OrderResponse() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  String value for requestId.
     * @param  status  String value for status.
     */
    public OrderResponse(
            String requestId,
            String status) {
        this.requestId = requestId;
        this.status = status;
    }

    /**
     * Getter for RequestId.
     * @return Returns the String
     */
    @JsonGetter("requestId")
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * @param requestId Value for String
     */
    @JsonSetter("requestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Converts this OrderResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrderResponse [" + "requestId=" + requestId + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link OrderResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrderResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .requestId(getRequestId())
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link OrderResponse}.
     */
    public static class Builder {
        private String requestId;
        private String status;



        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link OrderResponse} object using the set fields.
         * @return {@link OrderResponse}
         */
        public OrderResponse build() {
            return new OrderResponse(requestId, status);
        }
    }
}
