/*
 * Bandwidth
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bandwidth.sdk.model;

import com.bandwidth.sdk.model.GetAsyncBulkLookupResponseData;
import com.bandwidth.sdk.model.LinkSchema;
import com.bandwidth.sdk.model.LookupErrorSchema;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAsyncBulkLookupResponse
 */
public class GetAsyncBulkLookupResponseTest {
    private final GetAsyncBulkLookupResponse model = new GetAsyncBulkLookupResponse();

    /**
     * Model tests for GetAsyncBulkLookupResponse
     */
    @Test
    public void testGetAsyncBulkLookupResponse() {
        // TODO: test GetAsyncBulkLookupResponse
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
