/*
 * Bandwidth
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bandwidth.sdk.unit.models;

import org.junit.jupiter.api.Test;

import java.time.OffsetDateTime;
import com.bandwidth.sdk.model.StatusCallback;
import com.bandwidth.sdk.model.StatusCallbackMessage;
import com.bandwidth.sdk.model.StatusCallbackTypeEnum;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.hamcrest.MatcherAssert.assertThat;

/**
 * Model tests for StatusCallback
 */
public class StatusCallbackTest {
    private final StatusCallback model = new StatusCallback()
            .time(OffsetDateTime.now())
            .eventTime(OffsetDateTime.now())
            .type(StatusCallbackTypeEnum.DELIVERED)
            .to("to")
            .description("description")
            .message(new StatusCallbackMessage())
            .errorCode(1234)
            .carrierName("carrierName");

    /**
     * Model tests for StatusCallback
     */
    @Test
    public void testStatusCallback() {
        assertThat(model, instanceOf(StatusCallback.class));
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        assertThat(model.getTime(), instanceOf(OffsetDateTime.class));
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    public void eventTimeTest() {
        assertThat(model.getEventTime(), instanceOf(OffsetDateTime.class));
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        assertThat(model.getType(), instanceOf(StatusCallbackTypeEnum.class));
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        assertThat(model.getTo(), instanceOf(String.class));
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        assertThat(model.getDescription(), instanceOf(String.class));
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        assertThat(model.getMessage(), instanceOf(StatusCallbackMessage.class));
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        assertThat(model.getErrorCode(), instanceOf(Integer.class));
    }

    /**
     * Test the property 'carrierName'
     */
    @Test
    public void carrierNameTest() {
        assertThat(model.getCarrierName(), instanceOf(String.class));
    }

}
