/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for AssociatedSipPeers type.
 */
public class AssociatedSipPeers {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<AssociatedSipPeer> associatedSipPeers;

    /**
     * Default constructor.
     */
    public AssociatedSipPeers() {
    }

    /**
     * Initialization constructor.
     * @param  associatedSipPeers  List of AssociatedSipPeer value for associatedSipPeers.
     */
    public AssociatedSipPeers(
            List<AssociatedSipPeer> associatedSipPeers) {
        this.associatedSipPeers = associatedSipPeers;
    }

    /**
     * Getter for AssociatedSipPeers.
     * @return Returns the List of AssociatedSipPeer
     */
    @JsonGetter("associatedSipPeers")
    @XmlElement(name = "AssociatedSipPeer")
    public List<AssociatedSipPeer> getAssociatedSipPeers() {
        return associatedSipPeers;
    }

    /**
     * Setter for AssociatedSipPeers.
     * @param associatedSipPeers Value for List of AssociatedSipPeer
     */
    @JsonSetter("associatedSipPeers")
    public void setAssociatedSipPeers(List<AssociatedSipPeer> associatedSipPeers) {
        this.associatedSipPeers = associatedSipPeers;
    }

    /**
     * Converts this AssociatedSipPeers into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AssociatedSipPeers [" + "associatedSipPeers=" + associatedSipPeers + "]";
    }

    /**
     * Builds a new {@link AssociatedSipPeers.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AssociatedSipPeers.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .associatedSipPeers(getAssociatedSipPeers());
        return builder;
    }

    /**
     * Class to build instances of {@link AssociatedSipPeers}.
     */
    public static class Builder {
        private List<AssociatedSipPeer> associatedSipPeers;



        /**
         * Setter for associatedSipPeers.
         * @param  associatedSipPeers  List of AssociatedSipPeer value for associatedSipPeers.
         * @return Builder
         */
        public Builder associatedSipPeers(List<AssociatedSipPeer> associatedSipPeers) {
            this.associatedSipPeers = associatedSipPeers;
            return this;
        }

        /**
         * Builds a new {@link AssociatedSipPeers} object using the set fields.
         * @return {@link AssociatedSipPeers}
         */
        public AssociatedSipPeers build() {
            return new AssociatedSipPeers(associatedSipPeers);
        }
    }
}
