/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * AttributeProvisionTypeEnum to be used.
 */
public enum AttributeProvisionTypeEnum {
    @javax.xml.bind.annotation.XmlEnumValue("ACCOUNT")
    ACCOUNT,

    @javax.xml.bind.annotation.XmlEnumValue("ELEMENT")
    ELEMENT,

    @javax.xml.bind.annotation.XmlEnumValue("GATEWAY")
    GATEWAY,

    @javax.xml.bind.annotation.XmlEnumValue("MTAP")
    MTAP,

    @javax.xml.bind.annotation.XmlEnumValue("MTEP")
    MTEP,

    @javax.xml.bind.annotation.XmlEnumValue("MOAP")
    MOAP,

    @javax.xml.bind.annotation.XmlEnumValue("MOEP")
    MOEP;


    private static TreeMap<String, AttributeProvisionTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ACCOUNT.value = "ACCOUNT";
        ELEMENT.value = "ELEMENT";
        GATEWAY.value = "GATEWAY";
        MTAP.value = "MTAP";
        MTEP.value = "MTEP";
        MOAP.value = "MOAP";
        MOEP.value = "MOEP";

        valueMap.put("ACCOUNT", ACCOUNT);
        valueMap.put("ELEMENT", ELEMENT);
        valueMap.put("GATEWAY", GATEWAY);
        valueMap.put("MTAP", MTAP);
        valueMap.put("MTEP", MTEP);
        valueMap.put("MOAP", MOAP);
        valueMap.put("MOEP", MOEP);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AttributeProvisionTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AttributeProvisionTypeEnum values to list of string values.
     * @param toConvert The list of AttributeProvisionTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AttributeProvisionTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AttributeProvisionTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 