/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for BreakOutCountry type.
 */
public class BreakOutCountry {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String name;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String alpha3Code;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer countryCode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<Integer> prefixDigits;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean authRequired;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean billingEnabled;

    /**
     * Default constructor.
     */
    public BreakOutCountry() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  alpha3Code  String value for alpha3Code.
     * @param  countryCode  Integer value for countryCode.
     * @param  prefixDigits  List of Integer value for prefixDigits.
     * @param  authRequired  Boolean value for authRequired.
     * @param  billingEnabled  Boolean value for billingEnabled.
     */
    public BreakOutCountry(
            String name,
            String alpha3Code,
            Integer countryCode,
            List<Integer> prefixDigits,
            Boolean authRequired,
            Boolean billingEnabled) {
        this.name = name;
        this.alpha3Code = alpha3Code;
        this.countryCode = countryCode;
        this.prefixDigits = prefixDigits;
        this.authRequired = authRequired;
        this.billingEnabled = billingEnabled;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @XmlElement(name = "Name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Alpha3Code.
     * @return Returns the String
     */
    @JsonGetter("alpha3Code")
    @XmlElement(name = "Alpha3Code")
    public String getAlpha3Code() {
        return alpha3Code;
    }

    /**
     * Setter for Alpha3Code.
     * @param alpha3Code Value for String
     */
    @JsonSetter("alpha3Code")
    public void setAlpha3Code(String alpha3Code) {
        this.alpha3Code = alpha3Code;
    }

    /**
     * Getter for CountryCode.
     * @return Returns the Integer
     */
    @JsonGetter("countryCode")
    @XmlElement(name = "CountryCode")
    public Integer getCountryCode() {
        return countryCode;
    }

    /**
     * Setter for CountryCode.
     * @param countryCode Value for Integer
     */
    @JsonSetter("countryCode")
    public void setCountryCode(Integer countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for PrefixDigits.
     * @return Returns the List of Integer
     */
    @JsonGetter("prefixDigits")
    @XmlElementWrapper(name = "PrefixDigits")
    @XmlElement(name = "Digits")
    public List<Integer> getPrefixDigits() {
        return prefixDigits;
    }

    /**
     * Setter for PrefixDigits.
     * @param prefixDigits Value for List of Integer
     */
    @JsonSetter("prefixDigits")
    public void setPrefixDigits(List<Integer> prefixDigits) {
        this.prefixDigits = prefixDigits;
    }

    /**
     * Getter for AuthRequired.
     * @return Returns the Boolean
     */
    @JsonGetter("authRequired")
    @XmlElement(name = "AuthRequired")
    public Boolean getAuthRequired() {
        return authRequired;
    }

    /**
     * Setter for AuthRequired.
     * @param authRequired Value for Boolean
     */
    @JsonSetter("authRequired")
    public void setAuthRequired(Boolean authRequired) {
        this.authRequired = authRequired;
    }

    /**
     * Getter for BillingEnabled.
     * @return Returns the Boolean
     */
    @JsonGetter("billingEnabled")
    @XmlElement(name = "BillingEnabled")
    public Boolean getBillingEnabled() {
        return billingEnabled;
    }

    /**
     * Setter for BillingEnabled.
     * @param billingEnabled Value for Boolean
     */
    @JsonSetter("billingEnabled")
    public void setBillingEnabled(Boolean billingEnabled) {
        this.billingEnabled = billingEnabled;
    }

    /**
     * Converts this BreakOutCountry into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BreakOutCountry [" + "name=" + name + ", alpha3Code=" + alpha3Code
                + ", countryCode=" + countryCode + ", prefixDigits=" + prefixDigits
                + ", authRequired=" + authRequired + ", billingEnabled=" + billingEnabled + "]";
    }

    /**
     * Builds a new {@link BreakOutCountry.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BreakOutCountry.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .alpha3Code(getAlpha3Code())
                .countryCode(getCountryCode())
                .prefixDigits(getPrefixDigits())
                .authRequired(getAuthRequired())
                .billingEnabled(getBillingEnabled());
        return builder;
    }

    /**
     * Class to build instances of {@link BreakOutCountry}.
     */
    public static class Builder {
        private String name;
        private String alpha3Code;
        private Integer countryCode;
        private List<Integer> prefixDigits;
        private Boolean authRequired;
        private Boolean billingEnabled;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for alpha3Code.
         * @param  alpha3Code  String value for alpha3Code.
         * @return Builder
         */
        public Builder alpha3Code(String alpha3Code) {
            this.alpha3Code = alpha3Code;
            return this;
        }

        /**
         * Setter for countryCode.
         * @param  countryCode  Integer value for countryCode.
         * @return Builder
         */
        public Builder countryCode(Integer countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        /**
         * Setter for prefixDigits.
         * @param  prefixDigits  List of Integer value for prefixDigits.
         * @return Builder
         */
        public Builder prefixDigits(List<Integer> prefixDigits) {
            this.prefixDigits = prefixDigits;
            return this;
        }

        /**
         * Setter for authRequired.
         * @param  authRequired  Boolean value for authRequired.
         * @return Builder
         */
        public Builder authRequired(Boolean authRequired) {
            this.authRequired = authRequired;
            return this;
        }

        /**
         * Setter for billingEnabled.
         * @param  billingEnabled  Boolean value for billingEnabled.
         * @return Builder
         */
        public Builder billingEnabled(Boolean billingEnabled) {
            this.billingEnabled = billingEnabled;
            return this;
        }

        /**
         * Builds a new {@link BreakOutCountry} object using the set fields.
         * @return {@link BreakOutCountry}
         */
        public BreakOutCountry build() {
            return new BreakOutCountry(name, alpha3Code, countryCode, prefixDigits, authRequired,
                    billingEnabled);
        }
    }
}
