/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for Csr type.
 */
public class Csr {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerOrderId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String workingOrBillingTelephoneNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String workingTelephoneNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String billingTelephoneNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String authorizingPersonName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String accountNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> workingTelephoneNumbersOnAccount;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private CsrServiceAddress serviceAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String accountTelephoneNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String endUserName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String authorizingUserName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerCode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String endUserPIN;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String endUserPassword;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String addressLineOne;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String city;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String state;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String zipCode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String typeOfService;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;

    /**
     * Default constructor.
     */
    public Csr() {
    }

    /**
     * Initialization constructor.
     * @param  customerOrderId  String value for customerOrderId.
     * @param  workingOrBillingTelephoneNumber  String value for workingOrBillingTelephoneNumber.
     * @param  workingTelephoneNumber  String value for workingTelephoneNumber.
     * @param  billingTelephoneNumber  String value for billingTelephoneNumber.
     * @param  customerName  String value for customerName.
     * @param  authorizingPersonName  String value for authorizingPersonName.
     * @param  accountNumber  String value for accountNumber.
     * @param  workingTelephoneNumbersOnAccount  List of String value for
     *         workingTelephoneNumbersOnAccount.
     * @param  serviceAddress  CsrServiceAddress value for serviceAddress.
     * @param  accountTelephoneNumber  String value for accountTelephoneNumber.
     * @param  endUserName  String value for endUserName.
     * @param  authorizingUserName  String value for authorizingUserName.
     * @param  customerCode  String value for customerCode.
     * @param  endUserPIN  String value for endUserPIN.
     * @param  endUserPassword  String value for endUserPassword.
     * @param  addressLineOne  String value for addressLineOne.
     * @param  city  String value for city.
     * @param  state  String value for state.
     * @param  zipCode  String value for zipCode.
     * @param  typeOfService  String value for typeOfService.
     * @param  status  String value for status.
     */
    public Csr(
            String customerOrderId,
            String workingOrBillingTelephoneNumber,
            String workingTelephoneNumber,
            String billingTelephoneNumber,
            String customerName,
            String authorizingPersonName,
            String accountNumber,
            List<String> workingTelephoneNumbersOnAccount,
            CsrServiceAddress serviceAddress,
            String accountTelephoneNumber,
            String endUserName,
            String authorizingUserName,
            String customerCode,
            String endUserPIN,
            String endUserPassword,
            String addressLineOne,
            String city,
            String state,
            String zipCode,
            String typeOfService,
            String status) {
        this.customerOrderId = customerOrderId;
        this.workingOrBillingTelephoneNumber = workingOrBillingTelephoneNumber;
        this.workingTelephoneNumber = workingTelephoneNumber;
        this.billingTelephoneNumber = billingTelephoneNumber;
        this.customerName = customerName;
        this.authorizingPersonName = authorizingPersonName;
        this.accountNumber = accountNumber;
        this.workingTelephoneNumbersOnAccount = workingTelephoneNumbersOnAccount;
        this.serviceAddress = serviceAddress;
        this.accountTelephoneNumber = accountTelephoneNumber;
        this.endUserName = endUserName;
        this.authorizingUserName = authorizingUserName;
        this.customerCode = customerCode;
        this.endUserPIN = endUserPIN;
        this.endUserPassword = endUserPassword;
        this.addressLineOne = addressLineOne;
        this.city = city;
        this.state = state;
        this.zipCode = zipCode;
        this.typeOfService = typeOfService;
        this.status = status;
    }

    /**
     * Getter for CustomerOrderId.
     * @return Returns the String
     */
    @JsonGetter("customerOrderId")
    @XmlElement(name = "CustomerOrderId")
    public String getCustomerOrderId() {
        return customerOrderId;
    }

    /**
     * Setter for CustomerOrderId.
     * @param customerOrderId Value for String
     */
    @JsonSetter("customerOrderId")
    public void setCustomerOrderId(String customerOrderId) {
        this.customerOrderId = customerOrderId;
    }

    /**
     * Getter for WorkingOrBillingTelephoneNumber.
     * @return Returns the String
     */
    @JsonGetter("workingOrBillingTelephoneNumber")
    @XmlElement(name = "WorkingOrBillingTelephoneNumber")
    public String getWorkingOrBillingTelephoneNumber() {
        return workingOrBillingTelephoneNumber;
    }

    /**
     * Setter for WorkingOrBillingTelephoneNumber.
     * @param workingOrBillingTelephoneNumber Value for String
     */
    @JsonSetter("workingOrBillingTelephoneNumber")
    public void setWorkingOrBillingTelephoneNumber(String workingOrBillingTelephoneNumber) {
        this.workingOrBillingTelephoneNumber = workingOrBillingTelephoneNumber;
    }

    /**
     * Getter for WorkingTelephoneNumber.
     * @return Returns the String
     */
    @JsonGetter("workingTelephoneNumber")
    @XmlElement(name = "WorkingTelephoneNumber")
    public String getWorkingTelephoneNumber() {
        return workingTelephoneNumber;
    }

    /**
     * Setter for WorkingTelephoneNumber.
     * @param workingTelephoneNumber Value for String
     */
    @JsonSetter("workingTelephoneNumber")
    public void setWorkingTelephoneNumber(String workingTelephoneNumber) {
        this.workingTelephoneNumber = workingTelephoneNumber;
    }

    /**
     * Getter for BillingTelephoneNumber.
     * @return Returns the String
     */
    @JsonGetter("billingTelephoneNumber")
    @XmlElement(name = "BillingTelephoneNumber")
    public String getBillingTelephoneNumber() {
        return billingTelephoneNumber;
    }

    /**
     * Setter for BillingTelephoneNumber.
     * @param billingTelephoneNumber Value for String
     */
    @JsonSetter("billingTelephoneNumber")
    public void setBillingTelephoneNumber(String billingTelephoneNumber) {
        this.billingTelephoneNumber = billingTelephoneNumber;
    }

    /**
     * Getter for CustomerName.
     * @return Returns the String
     */
    @JsonGetter("customerName")
    @XmlElement(name = "CustomerName")
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Setter for CustomerName.
     * @param customerName Value for String
     */
    @JsonSetter("customerName")
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Getter for AuthorizingPersonName.
     * @return Returns the String
     */
    @JsonGetter("authorizingPersonName")
    @XmlElement(name = "AuthorizingPersonName")
    public String getAuthorizingPersonName() {
        return authorizingPersonName;
    }

    /**
     * Setter for AuthorizingPersonName.
     * @param authorizingPersonName Value for String
     */
    @JsonSetter("authorizingPersonName")
    public void setAuthorizingPersonName(String authorizingPersonName) {
        this.authorizingPersonName = authorizingPersonName;
    }

    /**
     * Getter for AccountNumber.
     * @return Returns the String
     */
    @JsonGetter("accountNumber")
    @XmlElement(name = "AccountNumber")
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * @param accountNumber Value for String
     */
    @JsonSetter("accountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for WorkingTelephoneNumbersOnAccount.
     * @return Returns the List of String
     */
    @JsonGetter("workingTelephoneNumbersOnAccount")
    @XmlElementWrapper(name = "WorkingTelephoneNumbersOnAccount")
    @XmlElement(name = "TelephoneNumber")
    public List<String> getWorkingTelephoneNumbersOnAccount() {
        return workingTelephoneNumbersOnAccount;
    }

    /**
     * Setter for WorkingTelephoneNumbersOnAccount.
     * @param workingTelephoneNumbersOnAccount Value for List of String
     */
    @JsonSetter("workingTelephoneNumbersOnAccount")
    public void setWorkingTelephoneNumbersOnAccount(List<String> workingTelephoneNumbersOnAccount) {
        this.workingTelephoneNumbersOnAccount = workingTelephoneNumbersOnAccount;
    }

    /**
     * Getter for ServiceAddress.
     * @return Returns the CsrServiceAddress
     */
    @JsonGetter("serviceAddress")
    @XmlElement(name = "ServiceAddress")
    public CsrServiceAddress getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Setter for ServiceAddress.
     * @param serviceAddress Value for CsrServiceAddress
     */
    @JsonSetter("serviceAddress")
    public void setServiceAddress(CsrServiceAddress serviceAddress) {
        this.serviceAddress = serviceAddress;
    }

    /**
     * Getter for AccountTelephoneNumber.
     * @return Returns the String
     */
    @JsonGetter("accountTelephoneNumber")
    @XmlElement(name = "AccountTelephoneNumber")
    public String getAccountTelephoneNumber() {
        return accountTelephoneNumber;
    }

    /**
     * Setter for AccountTelephoneNumber.
     * @param accountTelephoneNumber Value for String
     */
    @JsonSetter("accountTelephoneNumber")
    public void setAccountTelephoneNumber(String accountTelephoneNumber) {
        this.accountTelephoneNumber = accountTelephoneNumber;
    }

    /**
     * Getter for EndUserName.
     * @return Returns the String
     */
    @JsonGetter("endUserName")
    @XmlElement(name = "EndUserName")
    public String getEndUserName() {
        return endUserName;
    }

    /**
     * Setter for EndUserName.
     * @param endUserName Value for String
     */
    @JsonSetter("endUserName")
    public void setEndUserName(String endUserName) {
        this.endUserName = endUserName;
    }

    /**
     * Getter for AuthorizingUserName.
     * @return Returns the String
     */
    @JsonGetter("authorizingUserName")
    @XmlElement(name = "AuthorizingUserName")
    public String getAuthorizingUserName() {
        return authorizingUserName;
    }

    /**
     * Setter for AuthorizingUserName.
     * @param authorizingUserName Value for String
     */
    @JsonSetter("authorizingUserName")
    public void setAuthorizingUserName(String authorizingUserName) {
        this.authorizingUserName = authorizingUserName;
    }

    /**
     * Getter for CustomerCode.
     * @return Returns the String
     */
    @JsonGetter("customerCode")
    @XmlElement(name = "CustomerCode")
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Setter for CustomerCode.
     * @param customerCode Value for String
     */
    @JsonSetter("customerCode")
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * Getter for EndUserPIN.
     * @return Returns the String
     */
    @JsonGetter("endUserPIN")
    @XmlElement(name = "EndUserPIN")
    public String getEndUserPIN() {
        return endUserPIN;
    }

    /**
     * Setter for EndUserPIN.
     * @param endUserPIN Value for String
     */
    @JsonSetter("endUserPIN")
    public void setEndUserPIN(String endUserPIN) {
        this.endUserPIN = endUserPIN;
    }

    /**
     * Getter for EndUserPassword.
     * @return Returns the String
     */
    @JsonGetter("endUserPassword")
    @XmlElement(name = "EndUserPassword")
    public String getEndUserPassword() {
        return endUserPassword;
    }

    /**
     * Setter for EndUserPassword.
     * @param endUserPassword Value for String
     */
    @JsonSetter("endUserPassword")
    public void setEndUserPassword(String endUserPassword) {
        this.endUserPassword = endUserPassword;
    }

    /**
     * Getter for AddressLineOne.
     * @return Returns the String
     */
    @JsonGetter("addressLineOne")
    @XmlElement(name = "AddressLine1")
    public String getAddressLineOne() {
        return addressLineOne;
    }

    /**
     * Setter for AddressLineOne.
     * @param addressLineOne Value for String
     */
    @JsonSetter("addressLineOne")
    public void setAddressLineOne(String addressLineOne) {
        this.addressLineOne = addressLineOne;
    }

    /**
     * Getter for City.
     * @return Returns the String
     */
    @JsonGetter("city")
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * @param city Value for String
     */
    @JsonSetter("city")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for State.
     * @return Returns the String
     */
    @JsonGetter("state")
    @XmlElement(name = "State")
    public String getState() {
        return state;
    }

    /**
     * Setter for State.
     * @param state Value for String
     */
    @JsonSetter("state")
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for ZipCode.
     * @return Returns the String
     */
    @JsonGetter("zipCode")
    @XmlElement(name = "ZIPCode")
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Setter for ZipCode.
     * @param zipCode Value for String
     */
    @JsonSetter("zipCode")
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * Getter for TypeOfService.
     * @return Returns the String
     */
    @JsonGetter("typeOfService")
    @XmlElement(name = "TypeOfService")
    public String getTypeOfService() {
        return typeOfService;
    }

    /**
     * Setter for TypeOfService.
     * @param typeOfService Value for String
     */
    @JsonSetter("typeOfService")
    public void setTypeOfService(String typeOfService) {
        this.typeOfService = typeOfService;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @XmlElement(name = "Status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Converts this Csr into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Csr [" + "customerOrderId=" + customerOrderId + ", workingOrBillingTelephoneNumber="
                + workingOrBillingTelephoneNumber + ", workingTelephoneNumber="
                + workingTelephoneNumber + ", billingTelephoneNumber=" + billingTelephoneNumber
                + ", customerName=" + customerName + ", authorizingPersonName="
                + authorizingPersonName + ", accountNumber=" + accountNumber
                + ", workingTelephoneNumbersOnAccount=" + workingTelephoneNumbersOnAccount
                + ", serviceAddress=" + serviceAddress + ", accountTelephoneNumber="
                + accountTelephoneNumber + ", endUserName=" + endUserName + ", authorizingUserName="
                + authorizingUserName + ", customerCode=" + customerCode + ", endUserPIN="
                + endUserPIN + ", endUserPassword=" + endUserPassword + ", addressLineOne="
                + addressLineOne + ", city=" + city + ", state=" + state + ", zipCode=" + zipCode
                + ", typeOfService=" + typeOfService + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link Csr.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Csr.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .customerOrderId(getCustomerOrderId())
                .workingOrBillingTelephoneNumber(getWorkingOrBillingTelephoneNumber())
                .workingTelephoneNumber(getWorkingTelephoneNumber())
                .billingTelephoneNumber(getBillingTelephoneNumber())
                .customerName(getCustomerName())
                .authorizingPersonName(getAuthorizingPersonName())
                .accountNumber(getAccountNumber())
                .workingTelephoneNumbersOnAccount(getWorkingTelephoneNumbersOnAccount())
                .serviceAddress(getServiceAddress())
                .accountTelephoneNumber(getAccountTelephoneNumber())
                .endUserName(getEndUserName())
                .authorizingUserName(getAuthorizingUserName())
                .customerCode(getCustomerCode())
                .endUserPIN(getEndUserPIN())
                .endUserPassword(getEndUserPassword())
                .addressLineOne(getAddressLineOne())
                .city(getCity())
                .state(getState())
                .zipCode(getZipCode())
                .typeOfService(getTypeOfService())
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link Csr}.
     */
    public static class Builder {
        private String customerOrderId;
        private String workingOrBillingTelephoneNumber;
        private String workingTelephoneNumber;
        private String billingTelephoneNumber;
        private String customerName;
        private String authorizingPersonName;
        private String accountNumber;
        private List<String> workingTelephoneNumbersOnAccount;
        private CsrServiceAddress serviceAddress;
        private String accountTelephoneNumber;
        private String endUserName;
        private String authorizingUserName;
        private String customerCode;
        private String endUserPIN;
        private String endUserPassword;
        private String addressLineOne;
        private String city;
        private String state;
        private String zipCode;
        private String typeOfService;
        private String status;



        /**
         * Setter for customerOrderId.
         * @param  customerOrderId  String value for customerOrderId.
         * @return Builder
         */
        public Builder customerOrderId(String customerOrderId) {
            this.customerOrderId = customerOrderId;
            return this;
        }

        /**
         * Setter for workingOrBillingTelephoneNumber.
         * @param  workingOrBillingTelephoneNumber  String value for
         *         workingOrBillingTelephoneNumber.
         * @return Builder
         */
        public Builder workingOrBillingTelephoneNumber(String workingOrBillingTelephoneNumber) {
            this.workingOrBillingTelephoneNumber = workingOrBillingTelephoneNumber;
            return this;
        }

        /**
         * Setter for workingTelephoneNumber.
         * @param  workingTelephoneNumber  String value for workingTelephoneNumber.
         * @return Builder
         */
        public Builder workingTelephoneNumber(String workingTelephoneNumber) {
            this.workingTelephoneNumber = workingTelephoneNumber;
            return this;
        }

        /**
         * Setter for billingTelephoneNumber.
         * @param  billingTelephoneNumber  String value for billingTelephoneNumber.
         * @return Builder
         */
        public Builder billingTelephoneNumber(String billingTelephoneNumber) {
            this.billingTelephoneNumber = billingTelephoneNumber;
            return this;
        }

        /**
         * Setter for customerName.
         * @param  customerName  String value for customerName.
         * @return Builder
         */
        public Builder customerName(String customerName) {
            this.customerName = customerName;
            return this;
        }

        /**
         * Setter for authorizingPersonName.
         * @param  authorizingPersonName  String value for authorizingPersonName.
         * @return Builder
         */
        public Builder authorizingPersonName(String authorizingPersonName) {
            this.authorizingPersonName = authorizingPersonName;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for workingTelephoneNumbersOnAccount.
         * @param  workingTelephoneNumbersOnAccount  List of String value for
         *         workingTelephoneNumbersOnAccount.
         * @return Builder
         */
        public Builder workingTelephoneNumbersOnAccount(
                List<String> workingTelephoneNumbersOnAccount) {
            this.workingTelephoneNumbersOnAccount = workingTelephoneNumbersOnAccount;
            return this;
        }

        /**
         * Setter for serviceAddress.
         * @param  serviceAddress  CsrServiceAddress value for serviceAddress.
         * @return Builder
         */
        public Builder serviceAddress(CsrServiceAddress serviceAddress) {
            this.serviceAddress = serviceAddress;
            return this;
        }

        /**
         * Setter for accountTelephoneNumber.
         * @param  accountTelephoneNumber  String value for accountTelephoneNumber.
         * @return Builder
         */
        public Builder accountTelephoneNumber(String accountTelephoneNumber) {
            this.accountTelephoneNumber = accountTelephoneNumber;
            return this;
        }

        /**
         * Setter for endUserName.
         * @param  endUserName  String value for endUserName.
         * @return Builder
         */
        public Builder endUserName(String endUserName) {
            this.endUserName = endUserName;
            return this;
        }

        /**
         * Setter for authorizingUserName.
         * @param  authorizingUserName  String value for authorizingUserName.
         * @return Builder
         */
        public Builder authorizingUserName(String authorizingUserName) {
            this.authorizingUserName = authorizingUserName;
            return this;
        }

        /**
         * Setter for customerCode.
         * @param  customerCode  String value for customerCode.
         * @return Builder
         */
        public Builder customerCode(String customerCode) {
            this.customerCode = customerCode;
            return this;
        }

        /**
         * Setter for endUserPIN.
         * @param  endUserPIN  String value for endUserPIN.
         * @return Builder
         */
        public Builder endUserPIN(String endUserPIN) {
            this.endUserPIN = endUserPIN;
            return this;
        }

        /**
         * Setter for endUserPassword.
         * @param  endUserPassword  String value for endUserPassword.
         * @return Builder
         */
        public Builder endUserPassword(String endUserPassword) {
            this.endUserPassword = endUserPassword;
            return this;
        }

        /**
         * Setter for addressLineOne.
         * @param  addressLineOne  String value for addressLineOne.
         * @return Builder
         */
        public Builder addressLineOne(String addressLineOne) {
            this.addressLineOne = addressLineOne;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  String value for state.
         * @return Builder
         */
        public Builder state(String state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for zipCode.
         * @param  zipCode  String value for zipCode.
         * @return Builder
         */
        public Builder zipCode(String zipCode) {
            this.zipCode = zipCode;
            return this;
        }

        /**
         * Setter for typeOfService.
         * @param  typeOfService  String value for typeOfService.
         * @return Builder
         */
        public Builder typeOfService(String typeOfService) {
            this.typeOfService = typeOfService;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link Csr} object using the set fields.
         * @return {@link Csr}
         */
        public Csr build() {
            return new Csr(customerOrderId, workingOrBillingTelephoneNumber, workingTelephoneNumber,
                    billingTelephoneNumber, customerName, authorizingPersonName, accountNumber,
                    workingTelephoneNumbersOnAccount, serviceAddress, accountTelephoneNumber,
                    endUserName, authorizingUserName, customerCode, endUserPIN, endUserPassword,
                    addressLineOne, city, state, zipCode, typeOfService, status);
        }
    }
}
