/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for GeocodeRequestAddress type.
 */
public class GeocodeRequestAddress {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String housePrefix;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String houseNo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String houseSuffix;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String preDirectional;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String streetName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String streetSuffix;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String postDirectional;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String addressLine2;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String city;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String stateCode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String zip;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String zip4;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String county;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String country;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String addressType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean resetAddressFields;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String latitude;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String longitude;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String addressline1;

    /**
     * Default constructor.
     */
    public GeocodeRequestAddress() {
    }

    /**
     * Initialization constructor.
     * @param  housePrefix  String value for housePrefix.
     * @param  houseNo  String value for houseNo.
     * @param  houseSuffix  String value for houseSuffix.
     * @param  preDirectional  String value for preDirectional.
     * @param  streetName  String value for streetName.
     * @param  streetSuffix  String value for streetSuffix.
     * @param  postDirectional  String value for postDirectional.
     * @param  addressLine2  String value for addressLine2.
     * @param  city  String value for city.
     * @param  stateCode  String value for stateCode.
     * @param  zip  String value for zip.
     * @param  zip4  String value for zip4.
     * @param  county  String value for county.
     * @param  country  String value for country.
     * @param  addressType  String value for addressType.
     * @param  resetAddressFields  Boolean value for resetAddressFields.
     * @param  latitude  String value for latitude.
     * @param  longitude  String value for longitude.
     * @param  addressline1  String value for addressline1.
     */
    public GeocodeRequestAddress(
            String housePrefix,
            String houseNo,
            String houseSuffix,
            String preDirectional,
            String streetName,
            String streetSuffix,
            String postDirectional,
            String addressLine2,
            String city,
            String stateCode,
            String zip,
            String zip4,
            String county,
            String country,
            String addressType,
            Boolean resetAddressFields,
            String latitude,
            String longitude,
            String addressline1) {
        this.housePrefix = housePrefix;
        this.houseNo = houseNo;
        this.houseSuffix = houseSuffix;
        this.preDirectional = preDirectional;
        this.streetName = streetName;
        this.streetSuffix = streetSuffix;
        this.postDirectional = postDirectional;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.stateCode = stateCode;
        this.zip = zip;
        this.zip4 = zip4;
        this.county = county;
        this.country = country;
        this.addressType = addressType;
        this.resetAddressFields = resetAddressFields;
        this.latitude = latitude;
        this.longitude = longitude;
        this.addressline1 = addressline1;
    }

    /**
     * Getter for HousePrefix.
     * @return Returns the String
     */
    @JsonGetter("housePrefix")
    @XmlElement(name = "HousePrefix")
    public String getHousePrefix() {
        return housePrefix;
    }

    /**
     * Setter for HousePrefix.
     * @param housePrefix Value for String
     */
    @JsonSetter("housePrefix")
    public void setHousePrefix(String housePrefix) {
        this.housePrefix = housePrefix;
    }

    /**
     * Getter for HouseNo.
     * @return Returns the String
     */
    @JsonGetter("houseNo")
    @XmlElement(name = "HouseNumber")
    public String getHouseNo() {
        return houseNo;
    }

    /**
     * Setter for HouseNo.
     * @param houseNo Value for String
     */
    @JsonSetter("houseNo")
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo;
    }

    /**
     * Getter for HouseSuffix.
     * @return Returns the String
     */
    @JsonGetter("houseSuffix")
    @XmlElement(name = "HouseSuffix")
    public String getHouseSuffix() {
        return houseSuffix;
    }

    /**
     * Setter for HouseSuffix.
     * @param houseSuffix Value for String
     */
    @JsonSetter("houseSuffix")
    public void setHouseSuffix(String houseSuffix) {
        this.houseSuffix = houseSuffix;
    }

    /**
     * Getter for PreDirectional.
     * @return Returns the String
     */
    @JsonGetter("preDirectional")
    @XmlElement(name = "PreDirectional")
    public String getPreDirectional() {
        return preDirectional;
    }

    /**
     * Setter for PreDirectional.
     * @param preDirectional Value for String
     */
    @JsonSetter("preDirectional")
    public void setPreDirectional(String preDirectional) {
        this.preDirectional = preDirectional;
    }

    /**
     * Getter for StreetName.
     * @return Returns the String
     */
    @JsonGetter("streetName")
    @XmlElement(name = "StreetName")
    public String getStreetName() {
        return streetName;
    }

    /**
     * Setter for StreetName.
     * @param streetName Value for String
     */
    @JsonSetter("streetName")
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * Getter for StreetSuffix.
     * @return Returns the String
     */
    @JsonGetter("streetSuffix")
    @XmlElement(name = "StreetSuffix")
    public String getStreetSuffix() {
        return streetSuffix;
    }

    /**
     * Setter for StreetSuffix.
     * @param streetSuffix Value for String
     */
    @JsonSetter("streetSuffix")
    public void setStreetSuffix(String streetSuffix) {
        this.streetSuffix = streetSuffix;
    }

    /**
     * Getter for PostDirectional.
     * @return Returns the String
     */
    @JsonGetter("postDirectional")
    @XmlElement(name = "PostDirectional")
    public String getPostDirectional() {
        return postDirectional;
    }

    /**
     * Setter for PostDirectional.
     * @param postDirectional Value for String
     */
    @JsonSetter("postDirectional")
    public void setPostDirectional(String postDirectional) {
        this.postDirectional = postDirectional;
    }

    /**
     * Getter for AddressLine2.
     * @return Returns the String
     */
    @JsonGetter("addressLine2")
    @XmlElement(name = "AddressLine2")
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Setter for AddressLine2.
     * @param addressLine2 Value for String
     */
    @JsonSetter("addressLine2")
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * Getter for City.
     * @return Returns the String
     */
    @JsonGetter("city")
    @XmlElement(name = "City")
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * @param city Value for String
     */
    @JsonSetter("city")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for StateCode.
     * @return Returns the String
     */
    @JsonGetter("stateCode")
    @XmlElement(name = "StateCode")
    public String getStateCode() {
        return stateCode;
    }

    /**
     * Setter for StateCode.
     * @param stateCode Value for String
     */
    @JsonSetter("stateCode")
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    /**
     * Getter for Zip.
     * @return Returns the String
     */
    @JsonGetter("zip")
    @XmlElement(name = "Zip")
    public String getZip() {
        return zip;
    }

    /**
     * Setter for Zip.
     * @param zip Value for String
     */
    @JsonSetter("zip")
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * Getter for Zip4.
     * @return Returns the String
     */
    @JsonGetter("zip4")
    @XmlElement(name = "PlusFour")
    public String getZip4() {
        return zip4;
    }

    /**
     * Setter for Zip4.
     * @param zip4 Value for String
     */
    @JsonSetter("zip4")
    public void setZip4(String zip4) {
        this.zip4 = zip4;
    }

    /**
     * Getter for County.
     * @return Returns the String
     */
    @JsonGetter("county")
    @XmlElement(name = "County")
    public String getCounty() {
        return county;
    }

    /**
     * Setter for County.
     * @param county Value for String
     */
    @JsonSetter("county")
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * Getter for Country.
     * @return Returns the String
     */
    @JsonGetter("country")
    @XmlElement(name = "Country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * @param country Value for String
     */
    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for AddressType.
     * @return Returns the String
     */
    @JsonGetter("addressType")
    @XmlElement(name = "AddressType")
    public String getAddressType() {
        return addressType;
    }

    /**
     * Setter for AddressType.
     * @param addressType Value for String
     */
    @JsonSetter("addressType")
    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    /**
     * Getter for ResetAddressFields.
     * @return Returns the Boolean
     */
    @JsonGetter("resetAddressFields")
    @XmlElement(name = "ResetAddressFields")
    public Boolean getResetAddressFields() {
        return resetAddressFields;
    }

    /**
     * Setter for ResetAddressFields.
     * @param resetAddressFields Value for Boolean
     */
    @JsonSetter("resetAddressFields")
    public void setResetAddressFields(Boolean resetAddressFields) {
        this.resetAddressFields = resetAddressFields;
    }

    /**
     * Getter for Latitude.
     * @return Returns the String
     */
    @JsonGetter("latitude")
    @XmlElement(name = "Latitude")
    public String getLatitude() {
        return latitude;
    }

    /**
     * Setter for Latitude.
     * @param latitude Value for String
     */
    @JsonSetter("latitude")
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for Longitude.
     * @return Returns the String
     */
    @JsonGetter("longitude")
    @XmlElement(name = "Longitude")
    public String getLongitude() {
        return longitude;
    }

    /**
     * Setter for Longitude.
     * @param longitude Value for String
     */
    @JsonSetter("longitude")
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for Addressline1.
     * @return Returns the String
     */
    @JsonGetter("addressline1")
    @XmlElement(name = "AddressLine1")
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * Setter for Addressline1.
     * @param addressline1 Value for String
     */
    @JsonSetter("addressline1")
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    /**
     * Converts this GeocodeRequestAddress into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeocodeRequestAddress [" + "housePrefix=" + housePrefix + ", houseNo=" + houseNo
                + ", houseSuffix=" + houseSuffix + ", preDirectional=" + preDirectional
                + ", streetName=" + streetName + ", streetSuffix=" + streetSuffix
                + ", postDirectional=" + postDirectional + ", addressLine2=" + addressLine2
                + ", city=" + city + ", stateCode=" + stateCode + ", zip=" + zip + ", zip4=" + zip4
                + ", county=" + county + ", country=" + country + ", addressType=" + addressType
                + ", resetAddressFields=" + resetAddressFields + ", latitude=" + latitude
                + ", longitude=" + longitude + ", addressline1=" + addressline1 + "]";
    }

    /**
     * Builds a new {@link GeocodeRequestAddress.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeocodeRequestAddress.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .housePrefix(getHousePrefix())
                .houseNo(getHouseNo())
                .houseSuffix(getHouseSuffix())
                .preDirectional(getPreDirectional())
                .streetName(getStreetName())
                .streetSuffix(getStreetSuffix())
                .postDirectional(getPostDirectional())
                .addressLine2(getAddressLine2())
                .city(getCity())
                .stateCode(getStateCode())
                .zip(getZip())
                .zip4(getZip4())
                .county(getCounty())
                .country(getCountry())
                .addressType(getAddressType())
                .resetAddressFields(getResetAddressFields())
                .latitude(getLatitude())
                .longitude(getLongitude())
                .addressline1(getAddressline1());
        return builder;
    }

    /**
     * Class to build instances of {@link GeocodeRequestAddress}.
     */
    public static class Builder {
        private String housePrefix;
        private String houseNo;
        private String houseSuffix;
        private String preDirectional;
        private String streetName;
        private String streetSuffix;
        private String postDirectional;
        private String addressLine2;
        private String city;
        private String stateCode;
        private String zip;
        private String zip4;
        private String county;
        private String country;
        private String addressType;
        private Boolean resetAddressFields;
        private String latitude;
        private String longitude;
        private String addressline1;



        /**
         * Setter for housePrefix.
         * @param  housePrefix  String value for housePrefix.
         * @return Builder
         */
        public Builder housePrefix(String housePrefix) {
            this.housePrefix = housePrefix;
            return this;
        }

        /**
         * Setter for houseNo.
         * @param  houseNo  String value for houseNo.
         * @return Builder
         */
        public Builder houseNo(String houseNo) {
            this.houseNo = houseNo;
            return this;
        }

        /**
         * Setter for houseSuffix.
         * @param  houseSuffix  String value for houseSuffix.
         * @return Builder
         */
        public Builder houseSuffix(String houseSuffix) {
            this.houseSuffix = houseSuffix;
            return this;
        }

        /**
         * Setter for preDirectional.
         * @param  preDirectional  String value for preDirectional.
         * @return Builder
         */
        public Builder preDirectional(String preDirectional) {
            this.preDirectional = preDirectional;
            return this;
        }

        /**
         * Setter for streetName.
         * @param  streetName  String value for streetName.
         * @return Builder
         */
        public Builder streetName(String streetName) {
            this.streetName = streetName;
            return this;
        }

        /**
         * Setter for streetSuffix.
         * @param  streetSuffix  String value for streetSuffix.
         * @return Builder
         */
        public Builder streetSuffix(String streetSuffix) {
            this.streetSuffix = streetSuffix;
            return this;
        }

        /**
         * Setter for postDirectional.
         * @param  postDirectional  String value for postDirectional.
         * @return Builder
         */
        public Builder postDirectional(String postDirectional) {
            this.postDirectional = postDirectional;
            return this;
        }

        /**
         * Setter for addressLine2.
         * @param  addressLine2  String value for addressLine2.
         * @return Builder
         */
        public Builder addressLine2(String addressLine2) {
            this.addressLine2 = addressLine2;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for stateCode.
         * @param  stateCode  String value for stateCode.
         * @return Builder
         */
        public Builder stateCode(String stateCode) {
            this.stateCode = stateCode;
            return this;
        }

        /**
         * Setter for zip.
         * @param  zip  String value for zip.
         * @return Builder
         */
        public Builder zip(String zip) {
            this.zip = zip;
            return this;
        }

        /**
         * Setter for zip4.
         * @param  zip4  String value for zip4.
         * @return Builder
         */
        public Builder zip4(String zip4) {
            this.zip4 = zip4;
            return this;
        }

        /**
         * Setter for county.
         * @param  county  String value for county.
         * @return Builder
         */
        public Builder county(String county) {
            this.county = county;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for addressType.
         * @param  addressType  String value for addressType.
         * @return Builder
         */
        public Builder addressType(String addressType) {
            this.addressType = addressType;
            return this;
        }

        /**
         * Setter for resetAddressFields.
         * @param  resetAddressFields  Boolean value for resetAddressFields.
         * @return Builder
         */
        public Builder resetAddressFields(Boolean resetAddressFields) {
            this.resetAddressFields = resetAddressFields;
            return this;
        }

        /**
         * Setter for latitude.
         * @param  latitude  String value for latitude.
         * @return Builder
         */
        public Builder latitude(String latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Setter for longitude.
         * @param  longitude  String value for longitude.
         * @return Builder
         */
        public Builder longitude(String longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * Setter for addressline1.
         * @param  addressline1  String value for addressline1.
         * @return Builder
         */
        public Builder addressline1(String addressline1) {
            this.addressline1 = addressline1;
            return this;
        }

        /**
         * Builds a new {@link GeocodeRequestAddress} object using the set fields.
         * @return {@link GeocodeRequestAddress}
         */
        public GeocodeRequestAddress build() {
            return new GeocodeRequestAddress(housePrefix, houseNo, houseSuffix, preDirectional,
                    streetName, streetSuffix, postDirectional, addressLine2, city, stateCode, zip,
                    zip4, county, country, addressType, resetAddressFields, latitude, longitude,
                    addressline1);
        }
    }
}
