/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for MmsFeatureMm4SettingsResponse type.
 */
public class MmsFeatureMm4SettingsResponse {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Mm4Settings payload;

    /**
     * Default constructor.
     */
    public MmsFeatureMm4SettingsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  payload  Mm4Settings value for payload.
     */
    public MmsFeatureMm4SettingsResponse(
            Mm4Settings payload) {
        this.payload = payload;
    }

    /**
     * Getter for Payload.
     * @return Returns the Mm4Settings
     */
    @JsonGetter("payload")
    @XmlElement(name = "mm4Settings")
    public Mm4Settings getPayload() {
        return payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for Mm4Settings
     */
    @JsonSetter("payload")
    public void setPayload(Mm4Settings payload) {
        this.payload = payload;
    }

    /**
     * Converts this MmsFeatureMm4SettingsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MmsFeatureMm4SettingsResponse [" + "payload=" + payload + "]";
    }

    /**
     * Builds a new {@link MmsFeatureMm4SettingsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MmsFeatureMm4SettingsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payload(getPayload());
        return builder;
    }

    /**
     * Class to build instances of {@link MmsFeatureMm4SettingsResponse}.
     */
    public static class Builder {
        private Mm4Settings payload;



        /**
         * Setter for payload.
         * @param  payload  Mm4Settings value for payload.
         * @return Builder
         */
        public Builder payload(Mm4Settings payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Builds a new {@link MmsFeatureMm4SettingsResponse} object using the set fields.
         * @return {@link MmsFeatureMm4SettingsResponse}
         */
        public MmsFeatureMm4SettingsResponse build() {
            return new MmsFeatureMm4SettingsResponse(payload);
        }
    }
}
