/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for Order type.
 */
public class Order {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String id;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String name;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String lastModifiedBy;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerOrderId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer siteId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer peerId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String orderCreateDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private BaseOrderType orderType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean partialAllowed;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean backOrderRequested;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean closeOrder;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> tnAttributes;

    /**
     * Default constructor.
     */
    public Order() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  lastModifiedBy  String value for lastModifiedBy.
     * @param  customerOrderId  String value for customerOrderId.
     * @param  siteId  Integer value for siteId.
     * @param  peerId  Integer value for peerId.
     * @param  orderCreateDate  String value for orderCreateDate.
     * @param  orderType  BaseOrderType value for orderType.
     * @param  partialAllowed  Boolean value for partialAllowed.
     * @param  backOrderRequested  Boolean value for backOrderRequested.
     * @param  closeOrder  Boolean value for closeOrder.
     * @param  tnAttributes  List of String value for tnAttributes.
     */
    public Order(
            String id,
            String name,
            String lastModifiedBy,
            String customerOrderId,
            Integer siteId,
            Integer peerId,
            String orderCreateDate,
            BaseOrderType orderType,
            Boolean partialAllowed,
            Boolean backOrderRequested,
            Boolean closeOrder,
            List<String> tnAttributes) {
        this.id = id;
        this.name = name;
        this.lastModifiedBy = lastModifiedBy;
        this.customerOrderId = customerOrderId;
        this.siteId = siteId;
        this.peerId = peerId;
        this.orderCreateDate = orderCreateDate;
        this.orderType = orderType;
        this.partialAllowed = partialAllowed;
        this.backOrderRequested = backOrderRequested;
        this.closeOrder = closeOrder;
        this.tnAttributes = tnAttributes;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    @XmlElement(name = "id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @XmlElement(name = "Name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for LastModifiedBy.
     * @return Returns the String
     */
    @JsonGetter("lastModifiedBy")
    @XmlElement(name = "LastModifiedBy")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * Setter for LastModifiedBy.
     * @param lastModifiedBy Value for String
     */
    @JsonSetter("lastModifiedBy")
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for CustomerOrderId.
     * @return Returns the String
     */
    @JsonGetter("customerOrderId")
    @XmlElement(name = "CustomerOrderId")
    public String getCustomerOrderId() {
        return customerOrderId;
    }

    /**
     * Setter for CustomerOrderId.
     * @param customerOrderId Value for String
     */
    @JsonSetter("customerOrderId")
    public void setCustomerOrderId(String customerOrderId) {
        this.customerOrderId = customerOrderId;
    }

    /**
     * Getter for SiteId.
     * @return Returns the Integer
     */
    @JsonGetter("siteId")
    @XmlElement(name = "SiteId")
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * Setter for SiteId.
     * @param siteId Value for Integer
     */
    @JsonSetter("siteId")
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * Getter for PeerId.
     * @return Returns the Integer
     */
    @JsonGetter("peerId")
    @XmlElement(name = "PeerId")
    public Integer getPeerId() {
        return peerId;
    }

    /**
     * Setter for PeerId.
     * @param peerId Value for Integer
     */
    @JsonSetter("peerId")
    public void setPeerId(Integer peerId) {
        this.peerId = peerId;
    }

    /**
     * Getter for OrderCreateDate.
     * @return Returns the String
     */
    @JsonGetter("orderCreateDate")
    @XmlElement(name = "OrderCreateDate")
    public String getOrderCreateDate() {
        return orderCreateDate;
    }

    /**
     * Setter for OrderCreateDate.
     * @param orderCreateDate Value for String
     */
    @JsonSetter("orderCreateDate")
    public void setOrderCreateDate(String orderCreateDate) {
        this.orderCreateDate = orderCreateDate;
    }

    /**
     * Getter for OrderType.
     * @return Returns the BaseOrderType
     */
    @JsonGetter("orderType")
    @XmlElement(name = "BaseOrderType")
    public BaseOrderType getOrderType() {
        return orderType;
    }

    /**
     * Setter for OrderType.
     * @param orderType Value for BaseOrderType
     */
    @JsonSetter("orderType")
    public void setOrderType(BaseOrderType orderType) {
        this.orderType = orderType;
    }

    /**
     * Getter for PartialAllowed.
     * @return Returns the Boolean
     */
    @JsonGetter("partialAllowed")
    @XmlElement(name = "PartialAllowed")
    public Boolean getPartialAllowed() {
        return partialAllowed;
    }

    /**
     * Setter for PartialAllowed.
     * @param partialAllowed Value for Boolean
     */
    @JsonSetter("partialAllowed")
    public void setPartialAllowed(Boolean partialAllowed) {
        this.partialAllowed = partialAllowed;
    }

    /**
     * Getter for BackOrderRequested.
     * @return Returns the Boolean
     */
    @JsonGetter("backOrderRequested")
    @XmlElement(name = "BackOrderRequested")
    public Boolean getBackOrderRequested() {
        return backOrderRequested;
    }

    /**
     * Setter for BackOrderRequested.
     * @param backOrderRequested Value for Boolean
     */
    @JsonSetter("backOrderRequested")
    public void setBackOrderRequested(Boolean backOrderRequested) {
        this.backOrderRequested = backOrderRequested;
    }

    /**
     * Getter for CloseOrder.
     * @return Returns the Boolean
     */
    @JsonGetter("closeOrder")
    @XmlElement(name = "CloseOrder")
    public Boolean getCloseOrder() {
        return closeOrder;
    }

    /**
     * Setter for CloseOrder.
     * @param closeOrder Value for Boolean
     */
    @JsonSetter("closeOrder")
    public void setCloseOrder(Boolean closeOrder) {
        this.closeOrder = closeOrder;
    }

    /**
     * Getter for TnAttributes.
     * @return Returns the List of String
     */
    @JsonGetter("tnAttributes")
    @XmlElementWrapper(name = "TnAttributes")
    @XmlElement(name = "TnAttribute")
    public List<String> getTnAttributes() {
        return tnAttributes;
    }

    /**
     * Setter for TnAttributes.
     * @param tnAttributes Value for List of String
     */
    @JsonSetter("tnAttributes")
    public void setTnAttributes(List<String> tnAttributes) {
        this.tnAttributes = tnAttributes;
    }

    /**
     * Converts this Order into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Order [" + "id=" + id + ", name=" + name + ", lastModifiedBy=" + lastModifiedBy
                + ", customerOrderId=" + customerOrderId + ", siteId=" + siteId + ", peerId="
                + peerId + ", orderCreateDate=" + orderCreateDate + ", orderType=" + orderType
                + ", partialAllowed=" + partialAllowed + ", backOrderRequested="
                + backOrderRequested + ", closeOrder=" + closeOrder + ", tnAttributes="
                + tnAttributes + "]";
    }

    /**
     * Builds a new {@link Order.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Order.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .name(getName())
                .lastModifiedBy(getLastModifiedBy())
                .customerOrderId(getCustomerOrderId())
                .siteId(getSiteId())
                .peerId(getPeerId())
                .orderCreateDate(getOrderCreateDate())
                .orderType(getOrderType())
                .partialAllowed(getPartialAllowed())
                .backOrderRequested(getBackOrderRequested())
                .closeOrder(getCloseOrder())
                .tnAttributes(getTnAttributes());
        return builder;
    }

    /**
     * Class to build instances of {@link Order}.
     */
    public static class Builder {
        private String id;
        private String name;
        private String lastModifiedBy;
        private String customerOrderId;
        private Integer siteId;
        private Integer peerId;
        private String orderCreateDate;
        private BaseOrderType orderType;
        private Boolean partialAllowed;
        private Boolean backOrderRequested;
        private Boolean closeOrder;
        private List<String> tnAttributes;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for lastModifiedBy.
         * @param  lastModifiedBy  String value for lastModifiedBy.
         * @return Builder
         */
        public Builder lastModifiedBy(String lastModifiedBy) {
            this.lastModifiedBy = lastModifiedBy;
            return this;
        }

        /**
         * Setter for customerOrderId.
         * @param  customerOrderId  String value for customerOrderId.
         * @return Builder
         */
        public Builder customerOrderId(String customerOrderId) {
            this.customerOrderId = customerOrderId;
            return this;
        }

        /**
         * Setter for siteId.
         * @param  siteId  Integer value for siteId.
         * @return Builder
         */
        public Builder siteId(Integer siteId) {
            this.siteId = siteId;
            return this;
        }

        /**
         * Setter for peerId.
         * @param  peerId  Integer value for peerId.
         * @return Builder
         */
        public Builder peerId(Integer peerId) {
            this.peerId = peerId;
            return this;
        }

        /**
         * Setter for orderCreateDate.
         * @param  orderCreateDate  String value for orderCreateDate.
         * @return Builder
         */
        public Builder orderCreateDate(String orderCreateDate) {
            this.orderCreateDate = orderCreateDate;
            return this;
        }

        /**
         * Setter for orderType.
         * @param  orderType  BaseOrderType value for orderType.
         * @return Builder
         */
        public Builder orderType(BaseOrderType orderType) {
            this.orderType = orderType;
            return this;
        }

        /**
         * Setter for partialAllowed.
         * @param  partialAllowed  Boolean value for partialAllowed.
         * @return Builder
         */
        public Builder partialAllowed(Boolean partialAllowed) {
            this.partialAllowed = partialAllowed;
            return this;
        }

        /**
         * Setter for backOrderRequested.
         * @param  backOrderRequested  Boolean value for backOrderRequested.
         * @return Builder
         */
        public Builder backOrderRequested(Boolean backOrderRequested) {
            this.backOrderRequested = backOrderRequested;
            return this;
        }

        /**
         * Setter for closeOrder.
         * @param  closeOrder  Boolean value for closeOrder.
         * @return Builder
         */
        public Builder closeOrder(Boolean closeOrder) {
            this.closeOrder = closeOrder;
            return this;
        }

        /**
         * Setter for tnAttributes.
         * @param  tnAttributes  List of String value for tnAttributes.
         * @return Builder
         */
        public Builder tnAttributes(List<String> tnAttributes) {
            this.tnAttributes = tnAttributes;
            return this;
        }

        /**
         * Builds a new {@link Order} object using the set fields.
         * @return {@link Order}
         */
        public Order build() {
            return new Order(id, name, lastModifiedBy, customerOrderId, siteId, peerId,
                    orderCreateDate, orderType, partialAllowed, backOrderRequested, closeOrder,
                    tnAttributes);
        }
    }
}
