/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.bandwidth.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * This is a model class for ReportInstance type.
 */
public class ReportInstance {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer id;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer reportId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String description;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperExportId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperHost;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperSessionId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String reportName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String outputFormat;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String pages;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperOutputFormat;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String requestedByUserName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer requestedForAccountId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDateTime requestedAt;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String expiresAtStr;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDateTime completedAt;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<ReportParameterValue> parameterValues;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private ReportInstanceErrorDetails errorDetails;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperReportStatusDisplay;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String jasperExportStatusDisplay;

    /**
     * Default constructor.
     */
    public ReportInstance() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  reportId  Integer value for reportId.
     * @param  jasperId  String value for jasperId.
     * @param  description  String value for description.
     * @param  jasperExportId  String value for jasperExportId.
     * @param  jasperHost  String value for jasperHost.
     * @param  jasperSessionId  String value for jasperSessionId.
     * @param  reportName  String value for reportName.
     * @param  outputFormat  String value for outputFormat.
     * @param  pages  String value for pages.
     * @param  status  String value for status.
     * @param  jasperOutputFormat  String value for jasperOutputFormat.
     * @param  requestedByUserName  String value for requestedByUserName.
     * @param  requestedForAccountId  Integer value for requestedForAccountId.
     * @param  requestedAt  LocalDateTime value for requestedAt.
     * @param  expiresAtStr  String value for expiresAtStr.
     * @param  completedAt  LocalDateTime value for completedAt.
     * @param  parameterValues  List of ReportParameterValue value for parameterValues.
     * @param  errorDetails  ReportInstanceErrorDetails value for errorDetails.
     * @param  jasperReportStatusDisplay  String value for jasperReportStatusDisplay.
     * @param  jasperExportStatusDisplay  String value for jasperExportStatusDisplay.
     */
    public ReportInstance(
            Integer id,
            Integer reportId,
            String jasperId,
            String description,
            String jasperExportId,
            String jasperHost,
            String jasperSessionId,
            String reportName,
            String outputFormat,
            String pages,
            String status,
            String jasperOutputFormat,
            String requestedByUserName,
            Integer requestedForAccountId,
            LocalDateTime requestedAt,
            String expiresAtStr,
            LocalDateTime completedAt,
            List<ReportParameterValue> parameterValues,
            ReportInstanceErrorDetails errorDetails,
            String jasperReportStatusDisplay,
            String jasperExportStatusDisplay) {
        this.id = id;
        this.reportId = reportId;
        this.jasperId = jasperId;
        this.description = description;
        this.jasperExportId = jasperExportId;
        this.jasperHost = jasperHost;
        this.jasperSessionId = jasperSessionId;
        this.reportName = reportName;
        this.outputFormat = outputFormat;
        this.pages = pages;
        this.status = status;
        this.jasperOutputFormat = jasperOutputFormat;
        this.requestedByUserName = requestedByUserName;
        this.requestedForAccountId = requestedForAccountId;
        this.requestedAt = requestedAt;
        this.expiresAtStr = expiresAtStr;
        this.completedAt = completedAt;
        this.parameterValues = parameterValues;
        this.errorDetails = errorDetails;
        this.jasperReportStatusDisplay = jasperReportStatusDisplay;
        this.jasperExportStatusDisplay = jasperExportStatusDisplay;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @XmlElement(name = "Id")
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for ReportId.
     * @return Returns the Integer
     */
    @JsonGetter("reportId")
    @XmlElement(name = "ReportId")
    public Integer getReportId() {
        return reportId;
    }

    /**
     * Setter for ReportId.
     * @param reportId Value for Integer
     */
    @JsonSetter("reportId")
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * Getter for JasperId.
     * @return Returns the String
     */
    @JsonGetter("jasperId")
    @XmlElement(name = "JasperId")
    public String getJasperId() {
        return jasperId;
    }

    /**
     * Setter for JasperId.
     * @param jasperId Value for String
     */
    @JsonSetter("jasperId")
    public void setJasperId(String jasperId) {
        this.jasperId = jasperId;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @XmlElement(name = "Description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for JasperExportId.
     * @return Returns the String
     */
    @JsonGetter("jasperExportId")
    @XmlElement(name = "JasperExportId")
    public String getJasperExportId() {
        return jasperExportId;
    }

    /**
     * Setter for JasperExportId.
     * @param jasperExportId Value for String
     */
    @JsonSetter("jasperExportId")
    public void setJasperExportId(String jasperExportId) {
        this.jasperExportId = jasperExportId;
    }

    /**
     * Getter for JasperHost.
     * @return Returns the String
     */
    @JsonGetter("jasperHost")
    @XmlElement(name = "JasperHost")
    public String getJasperHost() {
        return jasperHost;
    }

    /**
     * Setter for JasperHost.
     * @param jasperHost Value for String
     */
    @JsonSetter("jasperHost")
    public void setJasperHost(String jasperHost) {
        this.jasperHost = jasperHost;
    }

    /**
     * Getter for JasperSessionId.
     * @return Returns the String
     */
    @JsonGetter("jasperSessionId")
    @XmlElement(name = "JasperSessionId")
    public String getJasperSessionId() {
        return jasperSessionId;
    }

    /**
     * Setter for JasperSessionId.
     * @param jasperSessionId Value for String
     */
    @JsonSetter("jasperSessionId")
    public void setJasperSessionId(String jasperSessionId) {
        this.jasperSessionId = jasperSessionId;
    }

    /**
     * Getter for ReportName.
     * @return Returns the String
     */
    @JsonGetter("reportName")
    @XmlElement(name = "ReportName")
    public String getReportName() {
        return reportName;
    }

    /**
     * Setter for ReportName.
     * @param reportName Value for String
     */
    @JsonSetter("reportName")
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    /**
     * Getter for OutputFormat.
     * @return Returns the String
     */
    @JsonGetter("outputFormat")
    @XmlElement(name = "OutputFormat")
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Setter for OutputFormat.
     * @param outputFormat Value for String
     */
    @JsonSetter("outputFormat")
    public void setOutputFormat(String outputFormat) {
        this.outputFormat = outputFormat;
    }

    /**
     * Getter for Pages.
     * @return Returns the String
     */
    @JsonGetter("pages")
    @XmlElement(name = "Pages")
    public String getPages() {
        return pages;
    }

    /**
     * Setter for Pages.
     * @param pages Value for String
     */
    @JsonSetter("pages")
    public void setPages(String pages) {
        this.pages = pages;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @XmlElement(name = "Status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for JasperOutputFormat.
     * @return Returns the String
     */
    @JsonGetter("jasperOutputFormat")
    @XmlElement(name = "JasperOutputFormat")
    public String getJasperOutputFormat() {
        return jasperOutputFormat;
    }

    /**
     * Setter for JasperOutputFormat.
     * @param jasperOutputFormat Value for String
     */
    @JsonSetter("jasperOutputFormat")
    public void setJasperOutputFormat(String jasperOutputFormat) {
        this.jasperOutputFormat = jasperOutputFormat;
    }

    /**
     * Getter for RequestedByUserName.
     * @return Returns the String
     */
    @JsonGetter("requestedByUserName")
    @XmlElement(name = "RequestedByUserName")
    public String getRequestedByUserName() {
        return requestedByUserName;
    }

    /**
     * Setter for RequestedByUserName.
     * @param requestedByUserName Value for String
     */
    @JsonSetter("requestedByUserName")
    public void setRequestedByUserName(String requestedByUserName) {
        this.requestedByUserName = requestedByUserName;
    }

    /**
     * Getter for RequestedForAccountId.
     * @return Returns the Integer
     */
    @JsonGetter("requestedForAccountId")
    @XmlElement(name = "RequestedForAccountId")
    public Integer getRequestedForAccountId() {
        return requestedForAccountId;
    }

    /**
     * Setter for RequestedForAccountId.
     * @param requestedForAccountId Value for Integer
     */
    @JsonSetter("requestedForAccountId")
    public void setRequestedForAccountId(Integer requestedForAccountId) {
        this.requestedForAccountId = requestedForAccountId;
    }

    /**
     * Getter for RequestedAt.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("requestedAt")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    @XmlJavaTypeAdapter(DateTimeHelper.Rfc8601DateTimeAdapter.class)
    @XmlElement(name = "RequestedAt")
    public LocalDateTime getRequestedAt() {
        return requestedAt;
    }

    /**
     * Setter for RequestedAt.
     * @param requestedAt Value for LocalDateTime
     */
    @JsonSetter("requestedAt")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setRequestedAt(LocalDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }

    /**
     * Getter for ExpiresAtStr.
     * @return Returns the String
     */
    @JsonGetter("expiresAtStr")
    @XmlElement(name = "ExpiresAt")
    public String getExpiresAtStr() {
        return expiresAtStr;
    }

    /**
     * Setter for ExpiresAtStr.
     * @param expiresAtStr Value for String
     */
    @JsonSetter("expiresAtStr")
    public void setExpiresAtStr(String expiresAtStr) {
        this.expiresAtStr = expiresAtStr;
    }

    /**
     * Getter for CompletedAt.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("completedAt")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    @XmlJavaTypeAdapter(DateTimeHelper.Rfc8601DateTimeAdapter.class)
    @XmlElement(name = "CompletedAt")
    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    /**
     * Setter for CompletedAt.
     * @param completedAt Value for LocalDateTime
     */
    @JsonSetter("completedAt")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for ParameterValues.
     * @return Returns the List of ReportParameterValue
     */
    @JsonGetter("parameterValues")
    @XmlElementWrapper(name = "Parameters")
    @XmlElement(name = "ParameterValue")
    public List<ReportParameterValue> getParameterValues() {
        return parameterValues;
    }

    /**
     * Setter for ParameterValues.
     * @param parameterValues Value for List of ReportParameterValue
     */
    @JsonSetter("parameterValues")
    public void setParameterValues(List<ReportParameterValue> parameterValues) {
        this.parameterValues = parameterValues;
    }

    /**
     * Getter for ErrorDetails.
     * @return Returns the ReportInstanceErrorDetails
     */
    @JsonGetter("errorDetails")
    @XmlElement(name = "ErrorDetails")
    public ReportInstanceErrorDetails getErrorDetails() {
        return errorDetails;
    }

    /**
     * Setter for ErrorDetails.
     * @param errorDetails Value for ReportInstanceErrorDetails
     */
    @JsonSetter("errorDetails")
    public void setErrorDetails(ReportInstanceErrorDetails errorDetails) {
        this.errorDetails = errorDetails;
    }

    /**
     * Getter for JasperReportStatusDisplay.
     * @return Returns the String
     */
    @JsonGetter("jasperReportStatusDisplay")
    @XmlElement(name = "JasperReportStatus")
    public String getJasperReportStatusDisplay() {
        return jasperReportStatusDisplay;
    }

    /**
     * Setter for JasperReportStatusDisplay.
     * @param jasperReportStatusDisplay Value for String
     */
    @JsonSetter("jasperReportStatusDisplay")
    public void setJasperReportStatusDisplay(String jasperReportStatusDisplay) {
        this.jasperReportStatusDisplay = jasperReportStatusDisplay;
    }

    /**
     * Getter for JasperExportStatusDisplay.
     * @return Returns the String
     */
    @JsonGetter("jasperExportStatusDisplay")
    @XmlElement(name = "JasperExportStatus")
    public String getJasperExportStatusDisplay() {
        return jasperExportStatusDisplay;
    }

    /**
     * Setter for JasperExportStatusDisplay.
     * @param jasperExportStatusDisplay Value for String
     */
    @JsonSetter("jasperExportStatusDisplay")
    public void setJasperExportStatusDisplay(String jasperExportStatusDisplay) {
        this.jasperExportStatusDisplay = jasperExportStatusDisplay;
    }

    /**
     * Converts this ReportInstance into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReportInstance [" + "id=" + id + ", reportId=" + reportId + ", jasperId=" + jasperId
                + ", description=" + description + ", jasperExportId=" + jasperExportId
                + ", jasperHost=" + jasperHost + ", jasperSessionId=" + jasperSessionId
                + ", reportName=" + reportName + ", outputFormat=" + outputFormat + ", pages="
                + pages + ", status=" + status + ", jasperOutputFormat=" + jasperOutputFormat
                + ", requestedByUserName=" + requestedByUserName + ", requestedForAccountId="
                + requestedForAccountId + ", requestedAt=" + requestedAt + ", expiresAtStr="
                + expiresAtStr + ", completedAt=" + completedAt + ", parameterValues="
                + parameterValues + ", errorDetails=" + errorDetails
                + ", jasperReportStatusDisplay=" + jasperReportStatusDisplay
                + ", jasperExportStatusDisplay=" + jasperExportStatusDisplay + "]";
    }

    /**
     * Builds a new {@link ReportInstance.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReportInstance.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .reportId(getReportId())
                .jasperId(getJasperId())
                .description(getDescription())
                .jasperExportId(getJasperExportId())
                .jasperHost(getJasperHost())
                .jasperSessionId(getJasperSessionId())
                .reportName(getReportName())
                .outputFormat(getOutputFormat())
                .pages(getPages())
                .status(getStatus())
                .jasperOutputFormat(getJasperOutputFormat())
                .requestedByUserName(getRequestedByUserName())
                .requestedForAccountId(getRequestedForAccountId())
                .requestedAt(getRequestedAt())
                .expiresAtStr(getExpiresAtStr())
                .completedAt(getCompletedAt())
                .parameterValues(getParameterValues())
                .errorDetails(getErrorDetails())
                .jasperReportStatusDisplay(getJasperReportStatusDisplay())
                .jasperExportStatusDisplay(getJasperExportStatusDisplay());
        return builder;
    }

    /**
     * Class to build instances of {@link ReportInstance}.
     */
    public static class Builder {
        private Integer id;
        private Integer reportId;
        private String jasperId;
        private String description;
        private String jasperExportId;
        private String jasperHost;
        private String jasperSessionId;
        private String reportName;
        private String outputFormat;
        private String pages;
        private String status;
        private String jasperOutputFormat;
        private String requestedByUserName;
        private Integer requestedForAccountId;
        private LocalDateTime requestedAt;
        private String expiresAtStr;
        private LocalDateTime completedAt;
        private List<ReportParameterValue> parameterValues;
        private ReportInstanceErrorDetails errorDetails;
        private String jasperReportStatusDisplay;
        private String jasperExportStatusDisplay;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for reportId.
         * @param  reportId  Integer value for reportId.
         * @return Builder
         */
        public Builder reportId(Integer reportId) {
            this.reportId = reportId;
            return this;
        }

        /**
         * Setter for jasperId.
         * @param  jasperId  String value for jasperId.
         * @return Builder
         */
        public Builder jasperId(String jasperId) {
            this.jasperId = jasperId;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for jasperExportId.
         * @param  jasperExportId  String value for jasperExportId.
         * @return Builder
         */
        public Builder jasperExportId(String jasperExportId) {
            this.jasperExportId = jasperExportId;
            return this;
        }

        /**
         * Setter for jasperHost.
         * @param  jasperHost  String value for jasperHost.
         * @return Builder
         */
        public Builder jasperHost(String jasperHost) {
            this.jasperHost = jasperHost;
            return this;
        }

        /**
         * Setter for jasperSessionId.
         * @param  jasperSessionId  String value for jasperSessionId.
         * @return Builder
         */
        public Builder jasperSessionId(String jasperSessionId) {
            this.jasperSessionId = jasperSessionId;
            return this;
        }

        /**
         * Setter for reportName.
         * @param  reportName  String value for reportName.
         * @return Builder
         */
        public Builder reportName(String reportName) {
            this.reportName = reportName;
            return this;
        }

        /**
         * Setter for outputFormat.
         * @param  outputFormat  String value for outputFormat.
         * @return Builder
         */
        public Builder outputFormat(String outputFormat) {
            this.outputFormat = outputFormat;
            return this;
        }

        /**
         * Setter for pages.
         * @param  pages  String value for pages.
         * @return Builder
         */
        public Builder pages(String pages) {
            this.pages = pages;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for jasperOutputFormat.
         * @param  jasperOutputFormat  String value for jasperOutputFormat.
         * @return Builder
         */
        public Builder jasperOutputFormat(String jasperOutputFormat) {
            this.jasperOutputFormat = jasperOutputFormat;
            return this;
        }

        /**
         * Setter for requestedByUserName.
         * @param  requestedByUserName  String value for requestedByUserName.
         * @return Builder
         */
        public Builder requestedByUserName(String requestedByUserName) {
            this.requestedByUserName = requestedByUserName;
            return this;
        }

        /**
         * Setter for requestedForAccountId.
         * @param  requestedForAccountId  Integer value for requestedForAccountId.
         * @return Builder
         */
        public Builder requestedForAccountId(Integer requestedForAccountId) {
            this.requestedForAccountId = requestedForAccountId;
            return this;
        }

        /**
         * Setter for requestedAt.
         * @param  requestedAt  LocalDateTime value for requestedAt.
         * @return Builder
         */
        public Builder requestedAt(LocalDateTime requestedAt) {
            this.requestedAt = requestedAt;
            return this;
        }

        /**
         * Setter for expiresAtStr.
         * @param  expiresAtStr  String value for expiresAtStr.
         * @return Builder
         */
        public Builder expiresAtStr(String expiresAtStr) {
            this.expiresAtStr = expiresAtStr;
            return this;
        }

        /**
         * Setter for completedAt.
         * @param  completedAt  LocalDateTime value for completedAt.
         * @return Builder
         */
        public Builder completedAt(LocalDateTime completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * Setter for parameterValues.
         * @param  parameterValues  List of ReportParameterValue value for parameterValues.
         * @return Builder
         */
        public Builder parameterValues(List<ReportParameterValue> parameterValues) {
            this.parameterValues = parameterValues;
            return this;
        }

        /**
         * Setter for errorDetails.
         * @param  errorDetails  ReportInstanceErrorDetails value for errorDetails.
         * @return Builder
         */
        public Builder errorDetails(ReportInstanceErrorDetails errorDetails) {
            this.errorDetails = errorDetails;
            return this;
        }

        /**
         * Setter for jasperReportStatusDisplay.
         * @param  jasperReportStatusDisplay  String value for jasperReportStatusDisplay.
         * @return Builder
         */
        public Builder jasperReportStatusDisplay(String jasperReportStatusDisplay) {
            this.jasperReportStatusDisplay = jasperReportStatusDisplay;
            return this;
        }

        /**
         * Setter for jasperExportStatusDisplay.
         * @param  jasperExportStatusDisplay  String value for jasperExportStatusDisplay.
         * @return Builder
         */
        public Builder jasperExportStatusDisplay(String jasperExportStatusDisplay) {
            this.jasperExportStatusDisplay = jasperExportStatusDisplay;
            return this;
        }

        /**
         * Builds a new {@link ReportInstance} object using the set fields.
         * @return {@link ReportInstance}
         */
        public ReportInstance build() {
            return new ReportInstance(id, reportId, jasperId, description, jasperExportId,
                    jasperHost, jasperSessionId, reportName, outputFormat, pages, status,
                    jasperOutputFormat, requestedByUserName, requestedForAccountId, requestedAt,
                    expiresAtStr, completedAt, parameterValues, errorDetails,
                    jasperReportStatusDisplay, jasperExportStatusDisplay);
        }
    }
}
