/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for SmsHost type.
 */
public class SmsHost {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String hostName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String port;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Long hostId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer priority;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String username;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String password;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private ConnectionTypeEnum connectionType;

    /**
     * Default constructor.
     */
    public SmsHost() {
    }

    /**
     * Initialization constructor.
     * @param  hostName  String value for hostName.
     * @param  port  String value for port.
     * @param  hostId  Long value for hostId.
     * @param  priority  Integer value for priority.
     * @param  username  String value for username.
     * @param  password  String value for password.
     * @param  connectionType  ConnectionTypeEnum value for connectionType.
     */
    public SmsHost(
            String hostName,
            String port,
            Long hostId,
            Integer priority,
            String username,
            String password,
            ConnectionTypeEnum connectionType) {
        this.hostName = hostName;
        this.port = port;
        this.hostId = hostId;
        this.priority = priority;
        this.username = username;
        this.password = password;
        this.connectionType = connectionType;
    }

    /**
     * Getter for HostName.
     * @return Returns the String
     */
    @JsonGetter("hostName")
    @XmlElement(name = "HostName")
    public String getHostName() {
        return hostName;
    }

    /**
     * Setter for HostName.
     * @param hostName Value for String
     */
    @JsonSetter("hostName")
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    /**
     * Getter for Port.
     * @return Returns the String
     */
    @JsonGetter("port")
    @XmlElement(name = "Port")
    public String getPort() {
        return port;
    }

    /**
     * Setter for Port.
     * @param port Value for String
     */
    @JsonSetter("port")
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * Getter for HostId.
     * @return Returns the Long
     */
    @JsonGetter("hostId")
    @XmlElement(name = "HostId")
    public Long getHostId() {
        return hostId;
    }

    /**
     * Setter for HostId.
     * @param hostId Value for Long
     */
    @JsonSetter("hostId")
    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }

    /**
     * Getter for Priority.
     * @return Returns the Integer
     */
    @JsonGetter("priority")
    @XmlElement(name = "Priority")
    public Integer getPriority() {
        return priority;
    }

    /**
     * Setter for Priority.
     * @param priority Value for Integer
     */
    @JsonSetter("priority")
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * Getter for Username.
     * @return Returns the String
     */
    @JsonGetter("username")
    @XmlElement(name = "Username")
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for Password.
     * @return Returns the String
     */
    @JsonGetter("password")
    @XmlElement(name = "Password")
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for ConnectionType.
     * @return Returns the ConnectionTypeEnum
     */
    @JsonGetter("connectionType")
    @XmlElement(name = "ConnectionType")
    public ConnectionTypeEnum getConnectionType() {
        return connectionType;
    }

    /**
     * Setter for ConnectionType.
     * @param connectionType Value for ConnectionTypeEnum
     */
    @JsonSetter("connectionType")
    public void setConnectionType(ConnectionTypeEnum connectionType) {
        this.connectionType = connectionType;
    }

    /**
     * Converts this SmsHost into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SmsHost [" + "hostName=" + hostName + ", port=" + port + ", hostId=" + hostId
                + ", priority=" + priority + ", username=" + username + ", password=" + password
                + ", connectionType=" + connectionType + "]";
    }

    /**
     * Builds a new {@link SmsHost.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SmsHost.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hostName(getHostName())
                .port(getPort())
                .hostId(getHostId())
                .priority(getPriority())
                .username(getUsername())
                .password(getPassword())
                .connectionType(getConnectionType());
        return builder;
    }

    /**
     * Class to build instances of {@link SmsHost}.
     */
    public static class Builder {
        private String hostName;
        private String port;
        private Long hostId;
        private Integer priority;
        private String username;
        private String password;
        private ConnectionTypeEnum connectionType;



        /**
         * Setter for hostName.
         * @param  hostName  String value for hostName.
         * @return Builder
         */
        public Builder hostName(String hostName) {
            this.hostName = hostName;
            return this;
        }

        /**
         * Setter for port.
         * @param  port  String value for port.
         * @return Builder
         */
        public Builder port(String port) {
            this.port = port;
            return this;
        }

        /**
         * Setter for hostId.
         * @param  hostId  Long value for hostId.
         * @return Builder
         */
        public Builder hostId(Long hostId) {
            this.hostId = hostId;
            return this;
        }

        /**
         * Setter for priority.
         * @param  priority  Integer value for priority.
         * @return Builder
         */
        public Builder priority(Integer priority) {
            this.priority = priority;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Setter for connectionType.
         * @param  connectionType  ConnectionTypeEnum value for connectionType.
         * @return Builder
         */
        public Builder connectionType(ConnectionTypeEnum connectionType) {
            this.connectionType = connectionType;
            return this;
        }

        /**
         * Builds a new {@link SmsHost} object using the set fields.
         * @return {@link SmsHost}
         */
        public SmsHost build() {
            return new SmsHost(hostName, port, hostId, priority, username, password,
                    connectionType);
        }
    }
}
