/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.dashboard.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

/**
 * This is a model class for TelephoneNumberStatusWrapper type.
 */
public class TelephoneNumberStatusWrapper {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<DetailedTelephoneNumberStatus> telephoneNumberStatusList;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String telephoneNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String tnStatus;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String lastModifiedDateInUtc;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String orderCreatedDateInUtc;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String orderId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String orderType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String inServiceDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer siteId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String peerGroup;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer accountId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private OrderDetailsReport tnDetails;

    /**
     * Default constructor.
     */
    public TelephoneNumberStatusWrapper() {
    }

    /**
     * Initialization constructor.
     * @param  telephoneNumberStatusList  List of DetailedTelephoneNumberStatus value for
     *         telephoneNumberStatusList.
     * @param  telephoneNumber  String value for telephoneNumber.
     * @param  tnStatus  String value for tnStatus.
     * @param  lastModifiedDateInUtc  String value for lastModifiedDateInUtc.
     * @param  orderCreatedDateInUtc  String value for orderCreatedDateInUtc.
     * @param  orderId  String value for orderId.
     * @param  orderType  String value for orderType.
     * @param  inServiceDate  String value for inServiceDate.
     * @param  siteId  Integer value for siteId.
     * @param  peerGroup  String value for peerGroup.
     * @param  accountId  Integer value for accountId.
     * @param  tnDetails  OrderDetailsReport value for tnDetails.
     */
    public TelephoneNumberStatusWrapper(
            List<DetailedTelephoneNumberStatus> telephoneNumberStatusList,
            String telephoneNumber,
            String tnStatus,
            String lastModifiedDateInUtc,
            String orderCreatedDateInUtc,
            String orderId,
            String orderType,
            String inServiceDate,
            Integer siteId,
            String peerGroup,
            Integer accountId,
            OrderDetailsReport tnDetails) {
        this.telephoneNumberStatusList = telephoneNumberStatusList;
        this.telephoneNumber = telephoneNumber;
        this.tnStatus = tnStatus;
        this.lastModifiedDateInUtc = lastModifiedDateInUtc;
        this.orderCreatedDateInUtc = orderCreatedDateInUtc;
        this.orderId = orderId;
        this.orderType = orderType;
        this.inServiceDate = inServiceDate;
        this.siteId = siteId;
        this.peerGroup = peerGroup;
        this.accountId = accountId;
        this.tnDetails = tnDetails;
    }

    /**
     * Getter for TelephoneNumberStatusList.
     * @return Returns the List of DetailedTelephoneNumberStatus
     */
    @JsonGetter("telephoneNumberStatusList")
    @XmlElementWrapper(name = "TelephoneNumberStatuses")
    @XmlElement(name = "DetailedTelephoneNumberStatus")
    public List<DetailedTelephoneNumberStatus> getTelephoneNumberStatusList() {
        return telephoneNumberStatusList;
    }

    /**
     * Setter for TelephoneNumberStatusList.
     * @param telephoneNumberStatusList Value for List of DetailedTelephoneNumberStatus
     */
    @JsonSetter("telephoneNumberStatusList")
    public void setTelephoneNumberStatusList(List<DetailedTelephoneNumberStatus> telephoneNumberStatusList) {
        this.telephoneNumberStatusList = telephoneNumberStatusList;
    }

    /**
     * Getter for TelephoneNumber.
     * @return Returns the String
     */
    @JsonGetter("telephoneNumber")
    @XmlElement(name = "TelephoneNumber")
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Setter for TelephoneNumber.
     * @param telephoneNumber Value for String
     */
    @JsonSetter("telephoneNumber")
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    /**
     * Getter for TnStatus.
     * @return Returns the String
     */
    @JsonGetter("tnStatus")
    @XmlElement(name = "Status")
    public String getTnStatus() {
        return tnStatus;
    }

    /**
     * Setter for TnStatus.
     * @param tnStatus Value for String
     */
    @JsonSetter("tnStatus")
    public void setTnStatus(String tnStatus) {
        this.tnStatus = tnStatus;
    }

    /**
     * Getter for LastModifiedDateInUtc.
     * @return Returns the String
     */
    @JsonGetter("lastModifiedDateInUtc")
    @XmlElement(name = "LastModifiedDate")
    public String getLastModifiedDateInUtc() {
        return lastModifiedDateInUtc;
    }

    /**
     * Setter for LastModifiedDateInUtc.
     * @param lastModifiedDateInUtc Value for String
     */
    @JsonSetter("lastModifiedDateInUtc")
    public void setLastModifiedDateInUtc(String lastModifiedDateInUtc) {
        this.lastModifiedDateInUtc = lastModifiedDateInUtc;
    }

    /**
     * Getter for OrderCreatedDateInUtc.
     * @return Returns the String
     */
    @JsonGetter("orderCreatedDateInUtc")
    @XmlElement(name = "OrderCreateDate")
    public String getOrderCreatedDateInUtc() {
        return orderCreatedDateInUtc;
    }

    /**
     * Setter for OrderCreatedDateInUtc.
     * @param orderCreatedDateInUtc Value for String
     */
    @JsonSetter("orderCreatedDateInUtc")
    public void setOrderCreatedDateInUtc(String orderCreatedDateInUtc) {
        this.orderCreatedDateInUtc = orderCreatedDateInUtc;
    }

    /**
     * Getter for OrderId.
     * @return Returns the String
     */
    @JsonGetter("orderId")
    @XmlElement(name = "OrderId")
    public String getOrderId() {
        return orderId;
    }

    /**
     * Setter for OrderId.
     * @param orderId Value for String
     */
    @JsonSetter("orderId")
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for OrderType.
     * @return Returns the String
     */
    @JsonGetter("orderType")
    @XmlElement(name = "OrderType")
    public String getOrderType() {
        return orderType;
    }

    /**
     * Setter for OrderType.
     * @param orderType Value for String
     */
    @JsonSetter("orderType")
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * Getter for InServiceDate.
     * @return Returns the String
     */
    @JsonGetter("inServiceDate")
    @XmlElement(name = "InServiceDate")
    public String getInServiceDate() {
        return inServiceDate;
    }

    /**
     * Setter for InServiceDate.
     * @param inServiceDate Value for String
     */
    @JsonSetter("inServiceDate")
    public void setInServiceDate(String inServiceDate) {
        this.inServiceDate = inServiceDate;
    }

    /**
     * Getter for SiteId.
     * @return Returns the Integer
     */
    @JsonGetter("siteId")
    @XmlElement(name = "SiteId")
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * Setter for SiteId.
     * @param siteId Value for Integer
     */
    @JsonSetter("siteId")
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * Getter for PeerGroup.
     * @return Returns the String
     */
    @JsonGetter("peerGroup")
    @XmlElement(name = "PeerGroup")
    public String getPeerGroup() {
        return peerGroup;
    }

    /**
     * Setter for PeerGroup.
     * @param peerGroup Value for String
     */
    @JsonSetter("peerGroup")
    public void setPeerGroup(String peerGroup) {
        this.peerGroup = peerGroup;
    }

    /**
     * Getter for AccountId.
     * @return Returns the Integer
     */
    @JsonGetter("accountId")
    @XmlElement(name = "AccountId")
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * Setter for AccountId.
     * @param accountId Value for Integer
     */
    @JsonSetter("accountId")
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for TnDetails.
     * @return Returns the OrderDetailsReport
     */
    @JsonGetter("tnDetails")
    @XmlElement(name = "TelephoneNumberDetails")
    public OrderDetailsReport getTnDetails() {
        return tnDetails;
    }

    /**
     * Setter for TnDetails.
     * @param tnDetails Value for OrderDetailsReport
     */
    @JsonSetter("tnDetails")
    public void setTnDetails(OrderDetailsReport tnDetails) {
        this.tnDetails = tnDetails;
    }

    /**
     * Converts this TelephoneNumberStatusWrapper into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TelephoneNumberStatusWrapper [" + "telephoneNumberStatusList="
                + telephoneNumberStatusList + ", telephoneNumber=" + telephoneNumber + ", tnStatus="
                + tnStatus + ", lastModifiedDateInUtc=" + lastModifiedDateInUtc
                + ", orderCreatedDateInUtc=" + orderCreatedDateInUtc + ", orderId=" + orderId
                + ", orderType=" + orderType + ", inServiceDate=" + inServiceDate + ", siteId="
                + siteId + ", peerGroup=" + peerGroup + ", accountId=" + accountId + ", tnDetails="
                + tnDetails + "]";
    }

    /**
     * Builds a new {@link TelephoneNumberStatusWrapper.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TelephoneNumberStatusWrapper.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .telephoneNumberStatusList(getTelephoneNumberStatusList())
                .telephoneNumber(getTelephoneNumber())
                .tnStatus(getTnStatus())
                .lastModifiedDateInUtc(getLastModifiedDateInUtc())
                .orderCreatedDateInUtc(getOrderCreatedDateInUtc())
                .orderId(getOrderId())
                .orderType(getOrderType())
                .inServiceDate(getInServiceDate())
                .siteId(getSiteId())
                .peerGroup(getPeerGroup())
                .accountId(getAccountId())
                .tnDetails(getTnDetails());
        return builder;
    }

    /**
     * Class to build instances of {@link TelephoneNumberStatusWrapper}.
     */
    public static class Builder {
        private List<DetailedTelephoneNumberStatus> telephoneNumberStatusList;
        private String telephoneNumber;
        private String tnStatus;
        private String lastModifiedDateInUtc;
        private String orderCreatedDateInUtc;
        private String orderId;
        private String orderType;
        private String inServiceDate;
        private Integer siteId;
        private String peerGroup;
        private Integer accountId;
        private OrderDetailsReport tnDetails;



        /**
         * Setter for telephoneNumberStatusList.
         * @param  telephoneNumberStatusList  List of DetailedTelephoneNumberStatus value for
         *         telephoneNumberStatusList.
         * @return Builder
         */
        public Builder telephoneNumberStatusList(
                List<DetailedTelephoneNumberStatus> telephoneNumberStatusList) {
            this.telephoneNumberStatusList = telephoneNumberStatusList;
            return this;
        }

        /**
         * Setter for telephoneNumber.
         * @param  telephoneNumber  String value for telephoneNumber.
         * @return Builder
         */
        public Builder telephoneNumber(String telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
            return this;
        }

        /**
         * Setter for tnStatus.
         * @param  tnStatus  String value for tnStatus.
         * @return Builder
         */
        public Builder tnStatus(String tnStatus) {
            this.tnStatus = tnStatus;
            return this;
        }

        /**
         * Setter for lastModifiedDateInUtc.
         * @param  lastModifiedDateInUtc  String value for lastModifiedDateInUtc.
         * @return Builder
         */
        public Builder lastModifiedDateInUtc(String lastModifiedDateInUtc) {
            this.lastModifiedDateInUtc = lastModifiedDateInUtc;
            return this;
        }

        /**
         * Setter for orderCreatedDateInUtc.
         * @param  orderCreatedDateInUtc  String value for orderCreatedDateInUtc.
         * @return Builder
         */
        public Builder orderCreatedDateInUtc(String orderCreatedDateInUtc) {
            this.orderCreatedDateInUtc = orderCreatedDateInUtc;
            return this;
        }

        /**
         * Setter for orderId.
         * @param  orderId  String value for orderId.
         * @return Builder
         */
        public Builder orderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

        /**
         * Setter for orderType.
         * @param  orderType  String value for orderType.
         * @return Builder
         */
        public Builder orderType(String orderType) {
            this.orderType = orderType;
            return this;
        }

        /**
         * Setter for inServiceDate.
         * @param  inServiceDate  String value for inServiceDate.
         * @return Builder
         */
        public Builder inServiceDate(String inServiceDate) {
            this.inServiceDate = inServiceDate;
            return this;
        }

        /**
         * Setter for siteId.
         * @param  siteId  Integer value for siteId.
         * @return Builder
         */
        public Builder siteId(Integer siteId) {
            this.siteId = siteId;
            return this;
        }

        /**
         * Setter for peerGroup.
         * @param  peerGroup  String value for peerGroup.
         * @return Builder
         */
        public Builder peerGroup(String peerGroup) {
            this.peerGroup = peerGroup;
            return this;
        }

        /**
         * Setter for accountId.
         * @param  accountId  Integer value for accountId.
         * @return Builder
         */
        public Builder accountId(Integer accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Setter for tnDetails.
         * @param  tnDetails  OrderDetailsReport value for tnDetails.
         * @return Builder
         */
        public Builder tnDetails(OrderDetailsReport tnDetails) {
            this.tnDetails = tnDetails;
            return this;
        }

        /**
         * Builds a new {@link TelephoneNumberStatusWrapper} object using the set fields.
         * @return {@link TelephoneNumberStatusWrapper}
         */
        public TelephoneNumberStatusWrapper build() {
            return new TelephoneNumberStatusWrapper(telephoneNumberStatusList, telephoneNumber,
                    tnStatus, lastModifiedDateInUtc, orderCreatedDateInUtc, orderId, orderType,
                    inServiceDate, siteId, peerGroup, accountId, tnDetails);
        }
    }
}
