/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.messaging.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BandwidthMessageItem type.
 */
public class BandwidthMessageItem {
    private String messageId;
    private String accountId;
    private String sourceTn;
    private String destinationTn;
    private String messageStatus;
    private String messageDirection;
    private String messageType;
    private Integer segmentCount;
    private Integer errorCode;
    private String receiveTime;
    private String carrierName;

    /**
     * Default constructor.
     */
    public BandwidthMessageItem() {
    }

    /**
     * Initialization constructor.
     * @param messageId String value for messageId.
     * @param accountId String value for accountId.
     * @param sourceTn String value for sourceTn.
     * @param destinationTn String value for destinationTn.
     * @param messageStatus String value for messageStatus.
     * @param messageDirection String value for messageDirection.
     * @param messageType String value for messageType.
     * @param segmentCount Integer value for segmentCount.
     * @param errorCode Integer value for errorCode.
     * @param receiveTime String value for receiveTime.
     * @param carrierName String value for carrierName.
     */
    public BandwidthMessageItem(
            String messageId,
            String accountId,
            String sourceTn,
            String destinationTn,
            String messageStatus,
            String messageDirection,
            String messageType,
            Integer segmentCount,
            Integer errorCode,
            String receiveTime,
            String carrierName) {
        this.messageId = messageId;
        this.accountId = accountId;
        this.sourceTn = sourceTn;
        this.destinationTn = destinationTn;
        this.messageStatus = messageStatus;
        this.messageDirection = messageDirection;
        this.messageType = messageType;
        this.segmentCount = segmentCount;
        this.errorCode = errorCode;
        this.receiveTime = receiveTime;
        this.carrierName = carrierName;
    }

    /**
     * Getter for MessageId.
     * The message id
     * @return Returns the String
     */
    @JsonGetter("messageId")
    public String getMessageId() {
        return this.messageId;
    }

    /**
     * Setter for MessageId.
     * The message id
     * @param messageId Value for String
     */
    @JsonSetter("messageId")
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * Getter for AccountId.
     * The account id of the message
     * @return Returns the String
     */
    @JsonGetter("accountId")
    public String getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for AccountId.
     * The account id of the message
     * @param accountId Value for String
     */
    @JsonSetter("accountId")
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for SourceTn.
     * The source phone number of the message
     * @return Returns the String
     */
    @JsonGetter("sourceTn")
    public String getSourceTn() {
        return this.sourceTn;
    }

    /**
     * Setter for SourceTn.
     * The source phone number of the message
     * @param sourceTn Value for String
     */
    @JsonSetter("sourceTn")
    public void setSourceTn(String sourceTn) {
        this.sourceTn = sourceTn;
    }

    /**
     * Getter for DestinationTn.
     * The recipient phone number of the message
     * @return Returns the String
     */
    @JsonGetter("destinationTn")
    public String getDestinationTn() {
        return this.destinationTn;
    }

    /**
     * Setter for DestinationTn.
     * The recipient phone number of the message
     * @param destinationTn Value for String
     */
    @JsonSetter("destinationTn")
    public void setDestinationTn(String destinationTn) {
        this.destinationTn = destinationTn;
    }

    /**
     * Getter for MessageStatus.
     * The status of the message
     * @return Returns the String
     */
    @JsonGetter("messageStatus")
    public String getMessageStatus() {
        return this.messageStatus;
    }

    /**
     * Setter for MessageStatus.
     * The status of the message
     * @param messageStatus Value for String
     */
    @JsonSetter("messageStatus")
    public void setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
    }

    /**
     * Getter for MessageDirection.
     * The direction of the message relative to Bandwidth. INBOUND or OUTBOUND
     * @return Returns the String
     */
    @JsonGetter("messageDirection")
    public String getMessageDirection() {
        return this.messageDirection;
    }

    /**
     * Setter for MessageDirection.
     * The direction of the message relative to Bandwidth. INBOUND or OUTBOUND
     * @param messageDirection Value for String
     */
    @JsonSetter("messageDirection")
    public void setMessageDirection(String messageDirection) {
        this.messageDirection = messageDirection;
    }

    /**
     * Getter for MessageType.
     * The type of message. sms or mms
     * @return Returns the String
     */
    @JsonGetter("messageType")
    public String getMessageType() {
        return this.messageType;
    }

    /**
     * Setter for MessageType.
     * The type of message. sms or mms
     * @param messageType Value for String
     */
    @JsonSetter("messageType")
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    /**
     * Getter for SegmentCount.
     * The number of segments the message was sent as
     * @return Returns the Integer
     */
    @JsonGetter("segmentCount")
    public Integer getSegmentCount() {
        return this.segmentCount;
    }

    /**
     * Setter for SegmentCount.
     * The number of segments the message was sent as
     * @param segmentCount Value for Integer
     */
    @JsonSetter("segmentCount")
    public void setSegmentCount(Integer segmentCount) {
        this.segmentCount = segmentCount;
    }

    /**
     * Getter for ErrorCode.
     * The numeric error code of the message
     * @return Returns the Integer
     */
    @JsonGetter("errorCode")
    public Integer getErrorCode() {
        return this.errorCode;
    }

    /**
     * Setter for ErrorCode.
     * The numeric error code of the message
     * @param errorCode Value for Integer
     */
    @JsonSetter("errorCode")
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * Getter for ReceiveTime.
     * The ISO 8601 datetime of the message
     * @return Returns the String
     */
    @JsonGetter("receiveTime")
    public String getReceiveTime() {
        return this.receiveTime;
    }

    /**
     * Setter for ReceiveTime.
     * The ISO 8601 datetime of the message
     * @param receiveTime Value for String
     */
    @JsonSetter("receiveTime")
    public void setReceiveTime(String receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * Getter for CarrierName.
     * The name of the carrier. Not currently supported for MMS, coming soon
     * @return Returns the String
     */
    @JsonGetter("carrierName")
    public String getCarrierName() {
        return this.carrierName;
    }

    /**
     * Setter for CarrierName.
     * The name of the carrier. Not currently supported for MMS, coming soon
     * @param carrierName Value for String
     */
    @JsonSetter("carrierName")
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * Converts this BandwidthMessageItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BandwidthMessageItem [" + "messageId=" + messageId + ", accountId=" + accountId
                + ", sourceTn=" + sourceTn + ", destinationTn=" + destinationTn + ", messageStatus="
                + messageStatus + ", messageDirection=" + messageDirection + ", messageType="
                + messageType + ", segmentCount=" + segmentCount + ", errorCode=" + errorCode
                + ", receiveTime=" + receiveTime + ", carrierName=" + carrierName + "]";
    }

    /**
     * Builds a new {@link BandwidthMessageItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BandwidthMessageItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .messageId(getMessageId())
                .accountId(getAccountId())
                .sourceTn(getSourceTn())
                .destinationTn(getDestinationTn())
                .messageStatus(getMessageStatus())
                .messageDirection(getMessageDirection())
                .messageType(getMessageType())
                .segmentCount(getSegmentCount())
                .errorCode(getErrorCode())
                .receiveTime(getReceiveTime())
                .carrierName(getCarrierName());
        return builder;
    }

    /**
     * Class to build instances of {@link BandwidthMessageItem}.
     */
    public static class Builder {
        private String messageId;
        private String accountId;
        private String sourceTn;
        private String destinationTn;
        private String messageStatus;
        private String messageDirection;
        private String messageType;
        private Integer segmentCount;
        private Integer errorCode;
        private String receiveTime;
        private String carrierName;



        /**
         * Setter for messageId.
         * @param messageId String value for messageId.
         * @return Builder
         */
        public Builder messageId(String messageId) {
            this.messageId = messageId;
            return this;
        }

        /**
         * Setter for accountId.
         * @param accountId String value for accountId.
         * @return Builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Setter for sourceTn.
         * @param sourceTn String value for sourceTn.
         * @return Builder
         */
        public Builder sourceTn(String sourceTn) {
            this.sourceTn = sourceTn;
            return this;
        }

        /**
         * Setter for destinationTn.
         * @param destinationTn String value for destinationTn.
         * @return Builder
         */
        public Builder destinationTn(String destinationTn) {
            this.destinationTn = destinationTn;
            return this;
        }

        /**
         * Setter for messageStatus.
         * @param messageStatus String value for messageStatus.
         * @return Builder
         */
        public Builder messageStatus(String messageStatus) {
            this.messageStatus = messageStatus;
            return this;
        }

        /**
         * Setter for messageDirection.
         * @param messageDirection String value for messageDirection.
         * @return Builder
         */
        public Builder messageDirection(String messageDirection) {
            this.messageDirection = messageDirection;
            return this;
        }

        /**
         * Setter for messageType.
         * @param messageType String value for messageType.
         * @return Builder
         */
        public Builder messageType(String messageType) {
            this.messageType = messageType;
            return this;
        }

        /**
         * Setter for segmentCount.
         * @param segmentCount Integer value for segmentCount.
         * @return Builder
         */
        public Builder segmentCount(Integer segmentCount) {
            this.segmentCount = segmentCount;
            return this;
        }

        /**
         * Setter for errorCode.
         * @param errorCode Integer value for errorCode.
         * @return Builder
         */
        public Builder errorCode(Integer errorCode) {
            this.errorCode = errorCode;
            return this;
        }

        /**
         * Setter for receiveTime.
         * @param receiveTime String value for receiveTime.
         * @return Builder
         */
        public Builder receiveTime(String receiveTime) {
            this.receiveTime = receiveTime;
            return this;
        }

        /**
         * Setter for carrierName.
         * @param carrierName String value for carrierName.
         * @return Builder
         */
        public Builder carrierName(String carrierName) {
            this.carrierName = carrierName;
            return this;
        }

        /**
         * Builds a new {@link BandwidthMessageItem} object using the set fields.
         * @return {@link BandwidthMessageItem}
         */
        public BandwidthMessageItem build() {
            return new BandwidthMessageItem(messageId, accountId, sourceTn, destinationTn,
                    messageStatus, messageDirection, messageType, segmentCount, errorCode,
                    receiveTime, carrierName);
        }
    }
}
