/*
 * BandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package com.bandwidth.messaging.exceptions;

import com.bandwidth.exceptions.ApiException;
import com.bandwidth.http.client.HttpContext;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MessagingExceptionErrorException type.
 */
public class MessagingExceptionErrorException
        extends ApiException {
    private static final long serialVersionUID = 5055941313450903910L;
    private String type;
    private String description;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public MessagingExceptionErrorException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    private void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    private void setDescription(String description) {
        this.description = description;
    }
}
