/*
 * Bandwidth
 * Bandwidth's Communication APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: letstalk@bandwidth.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Transcription;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TranscriptionList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-27T11:08:51.953012-04:00[America/New_York]")
public class TranscriptionList {
  public static final String SERIALIZED_NAME_TRANSCRIPTS = "transcripts";
  @SerializedName(SERIALIZED_NAME_TRANSCRIPTS)
  private List<Transcription> transcripts = null;

  public TranscriptionList() {
  }

  public TranscriptionList transcripts(List<Transcription> transcripts) {
    
    this.transcripts = transcripts;
    return this;
  }

  public TranscriptionList addTranscriptsItem(Transcription transcriptsItem) {
    if (this.transcripts == null) {
      this.transcripts = new ArrayList<>();
    }
    this.transcripts.add(transcriptsItem);
    return this;
  }

   /**
   * Get transcripts
   * @return transcripts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Transcription> getTranscripts() {
    return transcripts;
  }


  public void setTranscripts(List<Transcription> transcripts) {
    this.transcripts = transcripts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscriptionList transcriptionList = (TranscriptionList) o;
    return Objects.equals(this.transcripts, transcriptionList.transcripts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transcripts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscriptionList {\n");
    sb.append("    transcripts: ").append(toIndentedString(transcripts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transcripts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TranscriptionList
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (TranscriptionList.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in TranscriptionList is not found in the empty JSON string", TranscriptionList.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TranscriptionList.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TranscriptionList` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("transcripts") != null && !jsonObj.get("transcripts").isJsonNull()) {
        JsonArray jsonArraytranscripts = jsonObj.getAsJsonArray("transcripts");
        if (jsonArraytranscripts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("transcripts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `transcripts` to be an array in the JSON string but got `%s`", jsonObj.get("transcripts").toString()));
          }

          // validate the optional field `transcripts` (array)
          for (int i = 0; i < jsonArraytranscripts.size(); i++) {
            Transcription.validateJsonObject(jsonArraytranscripts.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TranscriptionList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TranscriptionList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TranscriptionList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TranscriptionList.class));

       return (TypeAdapter<T>) new TypeAdapter<TranscriptionList>() {
           @Override
           public void write(JsonWriter out, TranscriptionList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TranscriptionList read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TranscriptionList given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TranscriptionList
  * @throws IOException if the JSON string is invalid with respect to TranscriptionList
  */
  public static TranscriptionList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TranscriptionList.class);
  }

 /**
  * Convert an instance of TranscriptionList to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

