name: Deploy to Maven

on:
  release:
    types:
      - published
jobs:
  deploy:
    name: Push the Java SDK Maven
    if: ${{ !github.event.release.prerelease && github.event.release.target_commitish == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set release version
      run: |
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
            echo $RELEASE_VERSION
    - name: Java Maven Upload
      uses: ./.github/actions/deploy
      env:
        MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
        MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
        GPG_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        MESSAGING_APPLICATION_ID: ${{ secrets.MESSAGING_APPLICATION_ID }}
        MFA_MESSAGING_APPLICATION_ID: ${{ secrets.MFA_MESSAGING_APPLICATION_ID }}
        MFA_VOICE_APPLICATION_ID: ${{ secrets.MFA_VOICE_APPLICATION_ID }}
        PHONE_NUMBER_INBOUND: ${{ secrets.PHONE_NUMBER_INBOUND }}
        PHONE_NUMBER_MFA: ${{ secrets.PHONE_NUMBER_MFA }}
        PHONE_NUMBER_OUTBOUND: ${{ secrets.PHONE_NUMBER_OUTBOUND }}
        VOICE_APPLICATION_ID: ${{ secrets.VOICE_APPLICATION_ID }}
        VOICE_CALLBACK_URL: ${{ secrets.VOICE_CALLBACK_URL }}
