name: Check SDK

on:
    pull_request:
        branches:
          - main

jobs:
  deploy-java:
    name: Push the Java SDK Maven
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Java Maven Install
      uses: ./.github/actions/maven-install
      env:
        GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
