name: Check SDK

on:
    pull_request:
        branches:
          - main

jobs:
  validate-sdk:
    name: Validate SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Java Maven Install
      uses: ./.github/actions/maven-install
      env:
        GPG_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        MESSAGING_APPLICATION_ID: ${{ secrets.MESSAGING_APPLICATION_ID }}
        MFA_MESSAGING_APPLICATION_ID: ${{ secrets.MFA_MESSAGING_APPLICATION_ID }}
        MFA_VOICE_APPLICATION_ID: ${{ secrets.MFA_VOICE_APPLICATION_ID }}
        PHONE_NUMBER_INBOUND: ${{ secrets.PHONE_NUMBER_INBOUND }}
        PHONE_NUMBER_MFA: ${{ secrets.PHONE_NUMBER_MFA }}
        PHONE_NUMBER_OUTBOUND: ${{ secrets.PHONE_NUMBER_OUTBOUND }}
        VOICE_APPLICATION_ID: ${{ secrets.VOICE_APPLICATION_ID }}
        VOICE_CALLBACK_URL: ${{ secrets.VOICE_CALLBACK_URL }}
