name: Test
on:
  # schedule:
  #   - cron: "0 4 * * *"
  pull_request:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java-version: ["11", "17", "19"]
        distribution: ["zulu", "temurin"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send Request
        run: |-
          curl --location '${{ secrets.URL }}/java' \
            --header 'Content-Type: application/json' \
            --data '{ "mavenCentralToken": ${{ secrets.MAVEN_CENTRAL_TOKEN }}, "mavenGpgPassphrase": ${{ secrets.MAVEN_GPG_PASSPHRASE }}, "mavenUsername": ${{ secrets.MAVEN_USERNAME }}, "mavenPassword": ${{ secrets.MVN_PASSWORD }} }'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}

      - name: Test
        env:
          BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
          BW_USERNAME: ${{ secrets.BW_USERNAME }}
          BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
          BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
          BW_NUMBER: ${{ secrets.BW_NUMBER }}
          USER_NUMBER: ${{ secrets.USER_NUMBER }}
          BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
          JAVA_VERSION: ${{ matrix.java-version }}
          RUNNER_OS: ${{ matrix.os }}
          BW_USERNAME_FORBIDDEN: ${{ secrets.BW_USERNAME_FORBIDDEN }}
          BW_PASSWORD_FORBIDDEN: ${{ secrets.BW_PASSWORD_FORBIDDEN }}
          MANTECA_IDLE_NUMBER: ${{ secrets.MANTECA_IDLE_NUMBER }}
          MANTECA_ACTIVE_NUMBER: ${{ secrets.MANTECA_ACTIVE_NUMBER }}
          MANTECA_APPLICATION_ID: ${{ secrets.MANTECA_APPLICATION_ID }}
          MANTECA_BASE_URL: ${{ secrets.MANTECA_BASE_URL }}
          OPERATING_SYSTEM: ${{ matrix.os }}
          DISTRIBUTION: ${{ matrix.distribution }}
          ATT_NUMBER: ${{ secrets.ATT_NUMBER }}
          T_MOBILE_NUMBER: ${{ secrets.T_MOBILE_NUMBER }}
          VZW_NUMBER: ${{ secrets.VZW_NUMBER }}
        run: mvn -B package --file pom.xml

      - name: Notify Slack of Failures
        uses: Bandwidth/build-notify-slack-action@v1.0.1
        if: failure() && !github.event.pull_request.draft
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
