name: Test
on:
    schedule:
        - cron: "0 4 * * *"
    pull_request:
        branches:
            - main
            - feature/*
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2022, windows-2019, ubuntu-20.04, ubuntu-22.04]
                java-version: ["11", "17", "19"]
                distribution: ["zulu", "temurin"]
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: ${{ matrix.distribution }}
                  java-version: ${{ matrix.java-version }}

            - name: Test
              env:
                  BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
                  BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
                  BW_USERNAME: ${{ secrets.BW_USERNAME }}
                  BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
                  BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
                  BW_NUMBER: ${{ secrets.BW_NUMBER }}
                  USER_NUMBER: ${{ secrets.USER_NUMBER }}
                  BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
                  JAVA_VERSION: ${{ matrix.java-version }}
                  RUNNER_OS: ${{ matrix.os }}
                  BW_USERNAME_FORBIDDEN: ${{ secrets.BW_USERNAME_FORBIDDEN }}
                  BW_PASSWORD_FORBIDDEN: ${{ secrets.BW_PASSWORD_FORBIDDEN }}
                  MANTECA_IDLE_NUMBER: ${{ secrets.MANTECA_IDLE_NUMBER }}
                  MANTECA_ACTIVE_NUMBER: ${{ secrets.MANTECA_ACTIVE_NUMBER }}
                  MANTECA_APPLICATION_ID: ${{ secrets.MANTECA_APPLICATION_ID }}
                  MANTECA_BASE_URL: ${{ secrets.MANTECA_BASE_URL }}
                  OPERATING_SYSTEM: ${{ matrix.os }}
                  DISTRIBUTION: ${{ matrix.distribution }}
                  ATT_NUMBER: ${{ secrets.ATT_NUMBER }}
                  T_MOBILE_NUMBER: ${{ secrets.T_MOBILE_NUMBER }}
                  VZW_NUMBER: ${{ secrets.VZW_NUMBER }}
              run: mvn -B package --file pom.xml

    notify_for_failures:
        name: Notify for Failures
        needs: [test]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Notify Slack of Failures
              uses: Bandwidth/build-notify-slack-action@v2.0.0
              with:
                  job-status: failure
                  slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
                  slack-channel: ${{ secrets.SLACK_CHANNEL }}
