name: Test
on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-18.04, ubuntu-20.04]
        java-version: ["8", "11"]
        distribution: ["zulu", "temurin"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}

      - name: Test
        env:
          BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
          BW_USERNAME: ${{ secrets.BW_USERNAME }}
          BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
          BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
          BW_NUMBER: ${{ secrets.BW_NUMBER }}
          USER_NUMBER: ${{ secrets.USER_NUMBER }}
          BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
          ATT_NUMBER: ${{ secrets.ATT_NUMBER }}
          T_MOBILE_NUMBER: ${{ secrets.T_MOBILE_NUMBER }}
          VZW_NUMBER: ${{ secrets.VZW_NUMBER }}
        run: mvn -B package --file pom.xml

      - name: Notify Slack of Failures
        uses: Bandwidth/build-notify-slack-action@v1.0.0
        if: failure() && !github.event.pull_request.draft
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
